'use client';

import { useCallback, useEffect, useState } from 'react';
import { Badge, Button, Card, ConfirmDialog, EmptyState, fieldLabelStyle, Preloader } from '@devscribed/ds';
import { MESSAGES, REQUEST_MESSAGES, type VacationRequestStatus } from '@devscribed/validation';
import { useToast } from '@/toast';
import { VacationFinancialsModal } from './VacationFinancialsModal';
import { RequestVacationModal } from './RequestVacationModal';
import { RejectRequestModal } from './RejectRequestModal';
import { formatDateRange, formatWorkingDays } from './vacation-format';

/** The `financials` object in the GET `.../vacation` response (admin/manager only). */
export interface VacationFinancials {
  monthlySalary: number;
  clientHourlyRate: number;
  vacationReservePercent: number;
  isReservePercentManual: boolean;
  vacationDaysPerYear: number;
  currency: string;
}

/** The `balance` object. Numbers are real once spec 08 accrual is populated. */
interface VacationBalance {
  /** Currency reserve balance; `null` in the user-own payload (no money shown). */
  reserveBalance: number | null;
  availableDays: number;
  usedDays: number;
  pendingDays: number;
  totalDaysPerYear: number;
}

/** One row of the reserve ledger (spec 08). `null` on `VacationResponse.transactions`
 * for the user-own view; a (possibly empty) array for the admin/manager view. */
interface VacationTransaction {
  id: string;
  /** Spec 08 seeded `credit`/`expiry`; spec 09 adds `debit` (approval) and `refund`
   * (approved-cancel). Positive for `credit`/`refund`, negative for `expiry`/`debit`. */
  type: 'credit' | 'expiry' | 'debit' | 'refund';
  amount: number;
  billingPeriodMonth: number | null;
  billingPeriodYear: number | null;
  description: string | null;
  isAutoGenerated: boolean;
  /** ISO timestamp. */
  createdAt: string;
  /** Account id, or `null` for system/auto-generated transactions. */
  createdBy: string | null;
}

/** One vacation request (spec 09). `requests` is an array for the admin/manager view and
 * for a user viewing their own profile; `null` only where the tab does not show requests. */
export interface VacationRequest {
  id: string;
  /** 'YYYY-MM-DD'. */
  startDate: string;
  /** 'YYYY-MM-DD'. */
  endDate: string;
  workingDays: number;
  deductionAmount: number;
  status: VacationRequestStatus;
  requestedAt: string;
  reviewedAt: string | null;
  reviewedBy: string | null;
  reviewerComment: string | null;
  cancelledAt: string | null;
  cancelledBy: string | null;
}

interface VacationResponse {
  financials: VacationFinancials | null;
  balance: VacationBalance | null;
  /** `null` for the user-own view; an array (possibly empty) for admin/manager. */
  transactions: VacationTransaction[] | null;
  /** `null` where the tab shows no requests; otherwise an array (possibly empty). */
  requests: VacationRequest[] | null;
  canEdit: boolean;
  canReviewRequests: boolean;
  canSubmitRequest: boolean;
}

type PanelState =
  | { kind: 'loading' }
  | { kind: 'error'; message: string }
  | { kind: 'ready'; data: VacationResponse };

/**
 * Money rendered as `$3,000.00 USD` — two decimals with thousands separators. The
 * leading symbol is best-effort from `Intl.NumberFormat`'s currency style; when the
 * runtime lacks a symbol for the code it falls back to the bare formatted number plus
 * the raw code, so the ISO code is always present either way.
 */
function formatCurrency(amount: number, currency: string): string {
  try {
    const formatted = new Intl.NumberFormat(undefined, {
      style: 'currency',
      currency,
    }).format(amount);
    return `${formatted} ${currency}`;
  } catch {
    return `${amount.toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })} ${currency}`;
  }
}

/** Card-shaped bordered block — nested inside spec 05's outer `Card`, so it is a plain
 * `<section>` rather than a second DS `Card` (which would double-frame). */




/**
 * The Vacation tab panel (spec 07). Fetches `GET .../vacation` on mount, then renders
 * one of the four documented shapes (unconfigured admin/manager, unconfigured user,
 * configured admin/manager, configured user) purely from the payload's `financials` /
 * `balance` / `canEdit` — no client-side role re-derivation.
 */
export function VacationPanel({
  orgId,
  memberId,
  memberName,
}: {
  orgId: string;
  memberId: string;
  /** The viewed member's full name — shown as the requester in the reject modal. */
  memberName?: string;
}) {
  const { showToast } = useToast();
  const [state, setState] = useState<PanelState>({ kind: 'loading' });
  const [modalOpen, setModalOpen] = useState(false);
  const [requestModalOpen, setRequestModalOpen] = useState(false);
  const [rejectTarget, setRejectTarget] = useState<VacationRequest | null>(null);
  const [cancelTarget, setCancelTarget] = useState<VacationRequest | null>(null);
  const [cancelSaving, setCancelSaving] = useState(false);
  const [approvingId, setApprovingId] = useState<string | null>(null);

  const load = useCallback(async () => {
    setState({ kind: 'loading' });
    try {
      const response = await fetch(`/api/organizations/${orgId}/members/${memberId}/vacation`, {
        credentials: 'same-origin',
      });
      if (!response.ok) {
        const body = await response.json().catch(() => null);
        setState({ kind: 'error', message: body?.message ?? MESSAGES.generic });
        return;
      }
      const data = (await response.json()) as VacationResponse;
      setState({ kind: 'ready', data });
    } catch {
      setState({ kind: 'error', message: MESSAGES.generic });
    }
  }, [orgId, memberId]);

  useEffect(() => {
    void load();
  }, [load]);

  // Approve fires immediately (no modal); a self-approval 403 (unreachable via the action
  // matrix, but enforced server-side) surfaces as an error toast with the API message.
  async function handleApprove(request: VacationRequest) {
    if (approvingId) return;
    setApprovingId(request.id);
    try {
      const response = await fetch(
        `/api/organizations/${orgId}/members/${memberId}/vacation/requests/${request.id}/review`,
        {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          credentials: 'same-origin',
          body: JSON.stringify({ decision: 'approved' }),
        },
      );
      if (response.ok) {
        showToast('toast-request-approved', REQUEST_MESSAGES.toastApproved);
        await load();
        return;
      }
      const body = await response.json().catch(() => null);
      showToast('toast-request-approved', body?.message ?? REQUEST_MESSAGES.genericError, 'error');
    } catch {
      showToast('toast-request-approved', REQUEST_MESSAGES.genericError, 'error');
    } finally {
      setApprovingId(null);
    }
  }

  async function handleCancelConfirm() {
    const request = cancelTarget;
    if (!request || cancelSaving) return;
    setCancelSaving(true);
    try {
      const response = await fetch(
        `/api/organizations/${orgId}/members/${memberId}/vacation/requests/${request.id}/cancel`,
        { method: 'PUT', credentials: 'same-origin' },
      );
      if (response.ok) {
        const body = await response.json().catch(() => null);
        // `refunded` distinguishes the pending vs approved-cancel toast copy.
        const message = body?.refunded
          ? REQUEST_MESSAGES.toastCancelledApproved
          : REQUEST_MESSAGES.toastCancelledPending;
        setCancelTarget(null);
        setCancelSaving(false);
        showToast('toast-request-cancelled', message);
        await load();
        return;
      }
      const body = await response.json().catch(() => null);
      showToast('toast-request-cancelled', body?.message ?? REQUEST_MESSAGES.genericError, 'error');
    } catch {
      showToast('toast-request-cancelled', REQUEST_MESSAGES.genericError, 'error');
    }
    setCancelSaving(false);
  }

  if (state.kind === 'loading') return <Preloader data-testid="vacation-loading" />;

  if (state.kind === 'error') {
    return (
      <div style={{ padding: 'var(--space-6) 0', color: 'var(--text-secondary)', fontSize: 'var(--font-size-base)' }}>
        {state.message}
      </div>
    );
  }

  const { data } = state;
  const { financials, balance, transactions, requests, canEdit, canReviewRequests, canSubmitRequest } =
    data;

  // Unconfigured — no financials record exists yet (`balance` is null by contract).
  const unconfigured = balance === null;

  // Money (the per-row deduction amount) is an admin/manager signal — shown only in the
  // admin/manager payload, where `financials` is present. The user-own payload sends
  // `financials: null`, exactly as it suppresses the reserve amount (07/08).
  const showMoney = financials !== null;
  const currency = financials?.currency ?? 'USD';

  return (
    <>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)' }}>
        {unconfigured ? (
          <VacationEmptyState canEdit={canEdit} onSetup={() => setModalOpen(true)} />
        ) : (
          <>
            {financials && canEdit && (
              <FinancialsCard financials={financials} onEdit={() => setModalOpen(true)} />
            )}
            <BalanceCard balance={balance} currency={financials?.currency ?? null} />

            {/* Own-profile "Request vacation" button — disabled when no days remain. */}
            {canSubmitRequest && (
              <Button
                variant="primary"
                onClick={() => setRequestModalOpen(true)}
                disabled={balance.availableDays === 0}
                title={balance.availableDays === 0 ? 'No vacation days available' : undefined}
                data-testid="vacation-request-btn"
              >
                Request vacation
              </Button>
            )}

            {/* Requests list — rendered whenever the payload carries a (possibly empty) array. */}
            {requests !== null && (
              <RequestsCard
                requests={requests}
                showMoney={showMoney}
                currency={currency}
                canReviewRequests={canReviewRequests}
                canSubmitRequest={canSubmitRequest}
                approvingId={approvingId}
                actionsBusy={approvingId !== null || cancelSaving}
                onApprove={handleApprove}
                onReject={setRejectTarget}
                onCancel={setCancelTarget}
              />
            )}

            {/* Ledger is admin/manager-only — `transactions` is `null` for the user-own view. */}
            {transactions !== null && (
              <TransactionsTable transactions={transactions} currency={currency} />
            )}
          </>
        )}
      </div>

      {canEdit && (
        <VacationFinancialsModal
          orgId={orgId}
          memberId={memberId}
          open={modalOpen}
          financials={financials}
          onClose={() => setModalOpen(false)}
          onSaved={() => void load()}
        />
      )}

      {canSubmitRequest && balance && (
        <RequestVacationModal
          orgId={orgId}
          memberId={memberId}
          open={requestModalOpen}
          availableDays={balance.availableDays}
          onClose={() => setRequestModalOpen(false)}
          onSubmitted={() => void load()}
        />
      )}

      <RejectRequestModal
        orgId={orgId}
        memberId={memberId}
        request={rejectTarget}
        requesterName={memberName ?? null}
        onClose={() => setRejectTarget(null)}
        onRejected={() => void load()}
      />

      <CancelRequestDialog
        request={cancelTarget}
        saving={cancelSaving}
        onClose={() => {
          if (!cancelSaving) setCancelTarget(null);
        }}
        onConfirm={() => void handleCancelConfirm()}
      />
    </>
  );
}

function VacationEmptyState({ canEdit, onSetup }: { canEdit: boolean; onSetup: () => void }) {
  const message = canEdit
    ? // admin/manager empty copy — fixed verbatim by the business spec.
      'Vacation tracking has not been set up for this member yet.'
    : // user-own empty copy — fixed verbatim by the business spec.
      'Vacation tracking has not been set up for your account yet. Please contact your manager.';
  return (
    <EmptyState data-testid="vacation-empty-state">
      {message}
      {canEdit && (
        <div style={{ marginTop: 'var(--space-6)' }}>
          <Button variant="primary" onClick={onSetup} data-testid="vacation-setup-btn">
            Set up financials
          </Button>
        </div>
      )}
    </EmptyState>
  );
}

function FinancialsCard({
  financials,
  onEdit,
}: {
  financials: VacationFinancials;
  onEdit: () => void;
}) {
  const reserveSuffix = financials.isReservePercentManual ? '(manual)' : '(auto)';
  return (
    <Card
      data-testid="vacation-financials-card"
      title="Financial Settings"
      action={
        <Button onClick={onEdit} data-testid="vacation-financials-edit-btn">
          Edit
        </Button>
      }
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
        <Row label="Monthly salary" value={formatCurrency(financials.monthlySalary, financials.currency)} />
        <Row label="Client hourly rate" value={formatCurrency(financials.clientHourlyRate, financials.currency)} />
        <Row
          label="Reserve percentage"
          value={`${financials.vacationReservePercent.toFixed(2)}% ${reserveSuffix}`}
        />
        <Row label="Vacation days per year" value={String(financials.vacationDaysPerYear)} />
      </div>
    </Card>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 'var(--space-5)' }}>
      <span style={{ color: 'var(--text-secondary)', fontSize: 'var(--font-size-s)' }}>{label}</span>
      <span style={{ color: 'var(--text-primary)', fontSize: 'var(--font-size-base)', textAlign: 'right' }}>{value}</span>
    </div>
  );
}

function BalanceCard({ balance, currency }: { balance: VacationBalance; currency: string | null }) {
  return (
    <Card data-testid="vacation-balance-card" title="Vacation Balance">
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--space-7)' }}>
        <Stat testId="vacation-available-days" value={balance.availableDays} label="available" large />
        <Stat testId="vacation-used-days" value={balance.usedDays} label="used" />
        <Stat testId="vacation-pending-days" value={balance.pendingDays} label="pending" />
      </div>

      {/* Money only for admin/manager, and only when the reserve balance is present. */}
      {balance.reserveBalance != null && (
        <div
          data-testid="vacation-reserve-amount"
          style={{
            marginTop: 'var(--space-6)',
            fontSize: 'var(--font-size-base)',
            color: 'var(--text-primary)',
          }}
        >
          Reserve {formatCurrency(balance.reserveBalance, currency ?? 'USD')}
        </div>
      )}

      {/* User-own view: no money, an allowance line instead. */}
      {balance.reserveBalance == null && (
        <div
          style={{
            marginTop: 'var(--space-6)',
            fontSize: 'var(--font-size-s)',
            color: 'var(--text-tertiary)',
          }}
        >
          out of {balance.totalDaysPerYear} per year
        </div>
      )}
    </Card>
  );
}

/** Compact, deterministic date for a ledger row — `Jul 1`, matching the design mockup. */
function formatTxnDate(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(date);
}

/**
 * Reserve Transactions ledger (spec 08), admin/manager-only. Rendered from a non-null
 * `transactions` array — an empty array shows the fixed empty-state row. Five columns:
 * Date, Type, Amount (signed + coloured), Description, Created by. Rows arrive newest-first
 * from the payload and are not re-sorted here.
 */
function TransactionsTable({
  transactions,
  currency,
}: {
  transactions: VacationTransaction[];
  currency: string;
}) {
  /* The column headings take the field-label treatment (§74) — the same small-caps the rest
     of the system labels a value with — rather than a fourth uppercase style of their own. */
  const th: React.CSSProperties = {
    ...fieldLabelStyle,
    textAlign: 'left',
    padding: '0 0 var(--space-3)',
  };
  const td: React.CSSProperties = {
    padding: 'var(--space-3) 0',
    borderTop: 'var(--border-width-hairline) solid var(--border-subtle)',
    verticalAlign: 'top',
  };

  return (
    <Card data-testid="vacation-transactions-table" title="Reserve Transactions">
      {transactions.length === 0 ? (
        <div
          data-testid="vacation-no-transactions"
          style={{ color: 'var(--text-secondary)', fontSize: 'var(--font-size-base)' }}
        >
          No reserve transactions yet.
        </div>
      ) : (
        <table style={{ width: '100%', borderCollapse: 'collapse', tableLayout: 'auto' }}>
          <thead>
            <tr>
              <th scope="col" style={th}>Date</th>
              <th scope="col" style={th}>Type</th>
              <th scope="col" style={{ ...th, textAlign: 'right' }}>Amount</th>
              <th scope="col" style={th}>Description</th>
              <th scope="col" style={th}>Created by</th>
            </tr>
          </thead>
          <tbody>
            {transactions.map((t) => {
              // Sign + colour by type: `credit`/`refund` read as positive (green `+`),
              // `expiry`/`debit` as negative (red `−`). Label is the Title-cased type.
              const isPositive = t.type === 'credit' || t.type === 'refund';
              const sign = isPositive ? '+' : '−';
              const typeLabel = t.type.charAt(0).toUpperCase() + t.type.slice(1);
              return (
                <tr key={t.id}>
                  <td
                    style={{
                      ...td,
                      fontWeight: 'var(--font-weight-semibold)',
                      fontSize: 'var(--font-size-base)',
                      color: 'var(--text-primary)',
                      whiteSpace: 'nowrap',
                    }}
                  >
                    {formatTxnDate(t.createdAt)}
                  </td>
                  <td style={{ ...td, fontSize: 'var(--font-size-base)', color: 'var(--text-primary)' }}>
                    {typeLabel}
                    {t.isAutoGenerated && (
                      <span style={{ marginLeft: 'var(--space-1)', fontSize: 'var(--font-size-s)', color: 'var(--text-secondary)' }}>
                        (auto)
                      </span>
                    )}
                  </td>
                  <td
                    style={{
                      ...td,
                      textAlign: 'right',
                      whiteSpace: 'nowrap',
                      fontWeight: 'var(--font-weight-semibold)',
                      fontSize: 'var(--font-size-base)',
                      color: isPositive ? 'var(--status-success)' : 'var(--status-error)',
                    }}
                  >
                    {sign}
                    {formatCurrency(Math.abs(t.amount), currency)}
                  </td>
                  <td
                    style={{
                      ...td,
                      minWidth: 0,
                      fontSize: 'var(--font-size-base)',
                      color: 'var(--text-primary)',
                    }}
                  >
                    {t.description ?? ''}
                  </td>
                  <td style={{ ...td, fontSize: 'var(--font-size-s)', color: 'var(--text-tertiary)', whiteSpace: 'nowrap' }}>
                    {t.createdBy ?? 'System'}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      )}
    </Card>
  );
}

/** Status → DS `Badge` tone + label (spec 09 design). `inactive` resolves to red, so all
 * four statuses get a distinct existing tone — no token invented, no pill hand-built. */
const STATUS_META: Record<
  VacationRequestStatus,
  { tone: 'warning' | 'active' | 'inactive' | 'neutral'; label: string }
> = {
  pending: { tone: 'warning', label: 'Pending' },
  approved: { tone: 'active', label: 'Approved' },
  rejected: { tone: 'inactive', label: 'Rejected' },
  cancelled: { tone: 'neutral', label: 'Cancelled' },
};

/**
 * Vacation Requests / My Requests block (spec 09) — a fourth nested `<section>` between the
 * Balance card and the ledger. Heading is chosen by `canSubmitRequest` (own-profile → "My
 * Requests"). An empty array renders the fixed empty-state row; otherwise rows are shown
 * newest-first exactly as the payload orders them (no client re-sort).
 */
function RequestsCard({
  requests,
  showMoney,
  currency,
  canReviewRequests,
  canSubmitRequest,
  approvingId,
  actionsBusy,
  onApprove,
  onReject,
  onCancel,
}: {
  requests: VacationRequest[];
  showMoney: boolean;
  currency: string;
  canReviewRequests: boolean;
  canSubmitRequest: boolean;
  approvingId: string | null;
  actionsBusy: boolean;
  onApprove: (request: VacationRequest) => void;
  onReject: (request: VacationRequest) => void;
  onCancel: (request: VacationRequest) => void;
}) {
  const heading = canSubmitRequest ? 'My Requests' : 'Vacation Requests';
  return (
    <Card data-testid="vacation-requests-list" title={heading}>
      {requests.length === 0 ? (
        <div
          data-testid="vacation-no-requests"
          style={{ color: 'var(--text-secondary)', fontSize: 'var(--font-size-base)' }}
        >
          {REQUEST_MESSAGES.noRequests}
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          {requests.map((request, index) => (
            <RequestRow
              key={request.id}
              request={request}
              first={index === 0}
              showMoney={showMoney}
              currency={currency}
              canReviewRequests={canReviewRequests}
              canSubmitRequest={canSubmitRequest}
              approving={approvingId === request.id}
              actionsBusy={actionsBusy}
              onApprove={onApprove}
              onReject={onReject}
              onCancel={onCancel}
            />
          ))}
        </div>
      )}
    </Card>
  );
}

function RequestRow({
  request,
  first,
  showMoney,
  currency,
  canReviewRequests,
  canSubmitRequest,
  approving,
  actionsBusy,
  onApprove,
  onReject,
  onCancel,
}: {
  request: VacationRequest;
  first: boolean;
  showMoney: boolean;
  currency: string;
  canReviewRequests: boolean;
  canSubmitRequest: boolean;
  approving: boolean;
  actionsBusy: boolean;
  onApprove: (request: VacationRequest) => void;
  onReject: (request: VacationRequest) => void;
  onCancel: (request: VacationRequest) => void;
}) {
  const meta = STATUS_META[request.status];
  const isPending = request.status === 'pending';
  const isApproved = request.status === 'approved';

  // Own-profile/owner treatment wins over reviewer: on your own profile a pending request
  // shows only Cancel (never Approve/Reject) — this is TC-09-E2E-06's self-approval guard.
  const ownerView = canSubmitRequest;
  const reviewerView = canReviewRequests && !ownerView;
  const showApproveReject = reviewerView && isPending;
  const showCancel = (ownerView && isPending) || (reviewerView && isApproved);
  const hasActions = showApproveReject || showCancel;

  return (
    <div
      data-testid={`vacation-request-row-${request.id}`}
      style={{
        borderTop: first ? undefined : 'var(--border-width-hairline) solid var(--border-subtle)',
        padding: 'var(--space-4) 0',
        display: 'flex',
        flexDirection: 'column',
        gap: 'var(--space-2)',
      }}
    >
      <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 'var(--space-3)', minWidth: 0 }}>
        <span
          data-testid={`vacation-request-dates-${request.id}`}
          style={{
            fontWeight: 'var(--font-weight-semibold)',
            fontSize: 'var(--font-size-base)',
            color: 'var(--text-primary)',
            whiteSpace: 'nowrap',
          }}
        >
          {formatDateRange(request.startDate, request.endDate)}
        </span>
        <span
          data-testid={`vacation-request-days-${request.id}`}
          style={{ fontSize: 'var(--font-size-s)', color: 'var(--text-secondary)' }}
        >
          {formatWorkingDays(request.workingDays)}
        </span>
        <Badge status={meta.tone} data-testid={`vacation-request-status-${request.id}`}>
          {meta.label}
        </Badge>

        <div
          style={{
            marginLeft: 'auto',
            display: 'flex',
            alignItems: 'center',
            gap: 'var(--space-3)',
            flexWrap: 'wrap',
          }}
        >
          {showMoney && (
            <span
              style={{
                fontWeight: 'var(--font-weight-semibold)',
                fontSize: 'var(--font-size-base)',
                color: 'var(--text-primary)',
                whiteSpace: 'nowrap',
              }}
            >
              {formatCurrency(request.deductionAmount, currency)}
            </span>
          )}

          {hasActions && (
            <div style={{ display: 'flex', gap: 'var(--space-2)' }}>
              {showApproveReject && (
                <>
                  <Button
                    variant="primary"
                    preloader={approving}
                    disabled={actionsBusy && !approving}
                    onClick={() => onApprove(request)}
                    data-testid={`vacation-request-approve-${request.id}`}
                  >
                    Approve
                  </Button>
                  <Button
                    disabled={actionsBusy}
                    onClick={() => onReject(request)}
                    data-testid={`vacation-request-reject-${request.id}`}
                  >
                    Reject
                  </Button>
                </>
              )}
              {showCancel && (
                <Button
                  variant="delete"
                  disabled={actionsBusy}
                  onClick={() => onCancel(request)}
                  data-testid={`vacation-request-cancel-${request.id}`}
                >
                  Cancel
                </Button>
              )}
            </div>
          )}
        </div>
      </div>

      {request.status === 'rejected' && request.reviewerComment && (
        <div
          data-testid={`vacation-request-reviewer-comment-${request.id}`}
          style={{ fontSize: 'var(--font-size-s)', color: 'var(--text-tertiary)' }}
        >
          &ldquo;{request.reviewerComment}&rdquo;
        </div>
      )}
    </div>
  );
}

/**
 * The cancel confirmation (spec 09), on `ConfirmDialog` — the same collapse
 * `DeleteConfirmDialog` made, and §41 for the same reason: this dialog awaits a result the
 * reader has to see, so it passes `busy` and `closeOnAccept={false}` and the panel closes it
 * on the answer. Body copy still differs for a pending versus an approved request, because
 * only the approved one refunds a reserve.
 */
function CancelRequestDialog({
  request,
  saving,
  onClose,
  onConfirm,
}: {
  request: VacationRequest | null;
  saving: boolean;
  onClose: () => void;
  onConfirm: () => void;
}) {
  const isApproved = request?.status === 'approved';
  return (
    <ConfirmDialog
      open={request !== null}
      title="Cancel request"
      description={
        isApproved
          ? 'Cancel this approved vacation? The reserve will be refunded.'
          : 'Cancel this vacation request?'
      }
      acceptBtnText={saving ? 'Cancelling' : 'Cancel request'}
      declineBtnText="Keep it"
      busy={saving}
      closeOnAccept={false}
      onClose={onClose}
      onAccept={onConfirm}
      data-testid="vacation-cancel-confirm-dialog"
      acceptTestId="vacation-cancel-confirm-btn"
      declineTestId="vacation-cancel-dismiss-btn"
    />
  );
}

function Stat({
  testId,
  value,
  label,
  large,
}: {
  testId: string;
  value: number;
  label: string;
  large?: boolean;
}) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-1)' }}>
      <div
        data-testid={testId}
        style={{
          fontSize: large ? 'var(--headline-4-size)' : 'var(--headline-5-size)',
          fontWeight: large ? 'var(--headline-4-weight)' : 'var(--headline-5-weight)',
          letterSpacing: large ? 'var(--headline-4-tracking)' : 'var(--headline-5-tracking)',
          lineHeight: 1,
          color: 'var(--text-primary)',
        }}
      >
        {value}
      </div>
      <div style={{ fontSize: 'var(--font-size-s)', color: 'var(--text-secondary)' }}>{label}</div>
    </div>
  );
}

