using Devscribed.Admin.Web.Data;
using Devscribed.Admin.Web.Models;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace Devscribed.Admin.Web.Services;

public class VacationAccrualService
{
    private readonly AppDbContext _db;
    private readonly VacationLedgerService _ledger;

    public VacationAccrualService(AppDbContext db, VacationLedgerService ledger)
    {
        _db = db;
        _ledger = ledger;
    }

    public async Task<AccrualRunResult> RunAsync(Guid organizationId, int month, int year)
    {
        var activeMemberships = await _db.Memberships
            .Where(m => m.OrganizationId == organizationId && m.Status == "active")
            .ToListAsync();

        var processed = 0;
        var created = 0;
        var skipped = 0;

        var billingMonthStart = new DateOnly(year, month, 1);
        var billingMonthEnd = new DateOnly(year, month, DateTime.DaysInMonth(year, month));

        foreach (var membership in activeMemberships)
        {
            var financials = await _db.MemberFinancials.SingleOrDefaultAsync(f => f.MembershipId == membership.Id);
            if (financials == null)
                continue;

            processed++;

            var alreadyExists = await _db.VacationReserveTransactions.AnyAsync(t =>
                t.MembershipId == membership.Id
                && t.Type == VacationTransactionTypes.Credit
                && t.BillingPeriodMonth == month
                && t.BillingPeriodYear == year);

            if (alreadyExists)
            {
                skipped++;
                continue;
            }

            var snapshot = await _db.MemberFinancialsSnapshots
                .Where(s => s.MembershipId == membership.Id && s.EffectiveFrom <= billingMonthEnd)
                .OrderByDescending(s => s.EffectiveFrom)
                .FirstOrDefaultAsync();

            if (snapshot == null)
            {
                skipped++;
                continue;
            }

            var earliestSnapshot = await _db.MemberFinancialsSnapshots
                .Where(s => s.MembershipId == membership.Id)
                .OrderBy(s => s.EffectiveFrom)
                .FirstAsync();

            var fullCredit = VacationAccrualCalculator.CalculateFullMonthCredit(snapshot.ClientHourlyRate, snapshot.VacationReservePercent);

            var creditAmount = fullCredit;
            if (earliestSnapshot.EffectiveFrom > billingMonthStart && earliestSnapshot.EffectiveFrom <= billingMonthEnd)
            {
                var workingDaysInMonth = VacationAccrualCalculator.CountWeekdays(billingMonthStart, billingMonthEnd);
                var workingDaysFromConfig = VacationAccrualCalculator.CountWeekdays(earliestSnapshot.EffectiveFrom, billingMonthEnd);
                creditAmount = VacationAccrualCalculator.CalculateProratedCredit(fullCredit, workingDaysFromConfig, workingDaysInMonth);
            }

            var monthName = CultureInfo.InvariantCulture.DateTimeFormat.GetMonthName(month);

            _ledger.PostTransaction(
                membership.Id,
                VacationTransactionTypes.Credit,
                amount: creditAmount,
                description: $"{monthName} {year} accrual",
                isAutoGenerated: true,
                billingPeriodMonth: month,
                billingPeriodYear: year);

            created++;
        }

        await _db.SaveChangesAsync();

        return new AccrualRunResult(processed, created, skipped);
    }
}

public record AccrualRunResult(int Processed, int CreditsCreated, int Skipped);
