using Devscribed.Admin.Web.Data;
using Devscribed.Admin.Web.Models;
using Devscribed.Admin.Web.Validation;
using Microsoft.EntityFrameworkCore;

namespace Devscribed.Admin.Web.Services;

public class VacationService
{
    private readonly AppDbContext _db;
    private readonly VacationLedgerService _ledger;

    public VacationService(AppDbContext db, VacationLedgerService ledger)
    {
        _db = db;
        _ledger = ledger;
    }

    public async Task<VacationFetchResult> GetVacationAsync(
        Guid organizationId, Guid targetMembershipId, Guid callerMembershipId, string callerRole)
    {
        var target = await _db.Memberships
            .SingleOrDefaultAsync(m => m.Id == targetMembershipId && m.OrganizationId == organizationId);

        if (target == null)
            return VacationFetchResult.NotFound();

        var isOwnMembership = target.Id == callerMembershipId;
        if (!MemberPermissions.CanViewVacation(callerRole, isOwnMembership))
            return VacationFetchResult.Forbidden("You do not have permission to view this member's vacation data");

        var isFullView = callerRole is "admin" or "manager";

        // Year-end expiry: the first admin/manager action of a new year zeroes out any stale prior-year balance.
        if (isFullView)
            await _ledger.EnsureYearEndExpiryAsync(targetMembershipId);

        var financials = await _db.MemberFinancials.SingleOrDefaultAsync(f => f.MembershipId == targetMembershipId);

        VacationBalanceDto? balanceDto = null;
        List<VacationTransactionDto>? transactionDtos = null;

        var currentYear = DateTime.UtcNow.Year;
        var requests = await _db.VacationRequests
            .Where(r => r.MembershipId == targetMembershipId && (r.RequestedAt.Year == currentYear || r.StartDate.Year == currentYear))
            .OrderByDescending(r => r.RequestedAt)
            .ToListAsync();

        if (financials != null)
        {
            var usedDays = requests.Where(r => r.Status == VacationRequestStatuses.Approved && r.StartDate.Year == currentYear).Sum(r => r.WorkingDays);
            var pendingDays = requests.Where(r => r.Status == VacationRequestStatuses.Pending && r.RequestedAt.Year == currentYear).Sum(r => r.WorkingDays);
            var pendingHold = requests.Where(r => r.Status == VacationRequestStatuses.Pending && r.RequestedAt.Year == currentYear).Sum(r => r.DeductionAmount);

            var reserveBalance = await _db.VacationReserveTransactions
                .Where(t => t.MembershipId == targetMembershipId && t.CreatedAt.Year == currentYear)
                .SumAsync(t => (decimal?)t.Amount) ?? 0m;

            var dailySalary = VacationAccrualCalculator.CalculateDailySalary(financials.MonthlySalary);
            var availableDays = VacationAccrualCalculator.CalculateAvailableDays(
                reserveBalance, dailySalary, financials.VacationDaysPerYear, usedDays, pendingHold);

            balanceDto = new VacationBalanceDto
            {
                ReserveBalance = isFullView ? reserveBalance : null,
                AvailableDays = availableDays,
                UsedDays = usedDays,
                PendingDays = pendingDays,
                TotalDaysPerYear = financials.VacationDaysPerYear,
            };

            if (isFullView)
            {
                transactionDtos = await _db.VacationReserveTransactions
                    .Where(t => t.MembershipId == targetMembershipId)
                    .OrderByDescending(t => t.CreatedAt)
                    .Select(t => new VacationTransactionDto
                    {
                        Id = t.Id,
                        Type = t.Type,
                        Amount = t.Amount,
                        BillingPeriodMonth = t.BillingPeriodMonth,
                        BillingPeriodYear = t.BillingPeriodYear,
                        Description = t.Description,
                        IsAutoGenerated = t.IsAutoGenerated,
                        CreatedAt = t.CreatedAt,
                        CreatedByAccountId = t.CreatedByAccountId,
                    })
                    .ToListAsync();
            }
        }

        var dto = new VacationDto
        {
            Financials = (financials != null && isFullView)
                ? new VacationFinancialsDto
                {
                    MonthlySalary = financials.MonthlySalary,
                    ClientHourlyRate = financials.ClientHourlyRate,
                    VacationReservePercent = financials.VacationReservePercent,
                    IsReservePercentManual = financials.IsReservePercentManual,
                    VacationDaysPerYear = financials.VacationDaysPerYear,
                    Currency = financials.Currency,
                }
                : null,
            Balance = balanceDto,
            Requests = requests.Select(r => new VacationRequestDto
            {
                Id = r.Id,
                StartDate = r.StartDate,
                EndDate = r.EndDate,
                WorkingDays = r.WorkingDays,
                DeductionAmount = r.DeductionAmount,
                Status = r.Status,
                RequestedAt = r.RequestedAt,
                ReviewedAt = r.ReviewedAt,
                ReviewedByAccountId = r.ReviewedByAccountId,
                ReviewerComment = r.ReviewerComment,
                CancelledAt = r.CancelledAt,
                CancelledByAccountId = r.CancelledByAccountId,
                IsOwnRequest = r.MembershipId == callerMembershipId,
            }).ToList(),
            Transactions = transactionDtos,
            CanEdit = MemberPermissions.CanEditMemberFinancials(callerRole),
            CanReviewRequests = MemberPermissions.CanReviewVacationRequests(callerRole),
            CanSubmitRequest = MemberPermissions.CanSubmitVacationRequest(callerRole) && isOwnMembership,
        };

        return VacationFetchResult.Ok(dto);
    }

    public async Task<MemberFinancialsActionResult> UpdateFinancialsAsync(
        Guid organizationId, Guid targetMembershipId, Guid callerAccountId, string callerRole, UpdateMemberFinancialsRequest request)
    {
        if (!MemberPermissions.CanEditMemberFinancials(callerRole))
            return MemberFinancialsActionResult.Forbidden("You do not have permission to edit financial settings");

        var errors = MemberFinancialsValidator.ValidateAll(request);
        if (errors.Count > 0)
            return MemberFinancialsActionResult.FieldValidationError(errors);

        var target = await _db.Memberships
            .SingleOrDefaultAsync(m => m.Id == targetMembershipId && m.OrganizationId == organizationId);

        if (target == null)
            return MemberFinancialsActionResult.NotFound();

        if (target.Status == "removed")
            return MemberFinancialsActionResult.BadRequest("member_removed", "Cannot configure vacation for a removed member");

        var financials = await _db.MemberFinancials.SingleOrDefaultAsync(f => f.MembershipId == targetMembershipId);
        if (financials == null)
        {
            financials = new MemberFinancials { Id = Guid.NewGuid(), MembershipId = targetMembershipId };
            _db.MemberFinancials.Add(financials);
        }

        var effectivePercent = request.IsReservePercentManual
            ? request.VacationReservePercent!.Value
            : VacationReserveCalculator.CalculateReservePercent(
                request.MonthlySalary!.Value, request.ClientHourlyRate!.Value, request.VacationDaysPerYear!.Value);

        financials.MonthlySalary = request.MonthlySalary!.Value;
        financials.ClientHourlyRate = request.ClientHourlyRate!.Value;
        financials.VacationDaysPerYear = request.VacationDaysPerYear!.Value;
        financials.Currency = request.Currency!;
        financials.IsReservePercentManual = request.IsReservePercentManual;
        financials.VacationReservePercent = effectivePercent;
        financials.UpdatedAt = DateTime.UtcNow;
        financials.UpdatedByAccountId = callerAccountId;

        _db.MemberFinancialsSnapshots.Add(new MemberFinancialsSnapshot
        {
            Id = Guid.NewGuid(),
            MembershipId = targetMembershipId,
            MonthlySalary = financials.MonthlySalary,
            ClientHourlyRate = financials.ClientHourlyRate,
            VacationReservePercent = financials.VacationReservePercent,
            IsReservePercentManual = financials.IsReservePercentManual,
            VacationDaysPerYear = financials.VacationDaysPerYear,
            Currency = financials.Currency,
            EffectiveFrom = DateOnly.FromDateTime(DateTime.UtcNow),
            CreatedAt = DateTime.UtcNow,
        });

        await _db.SaveChangesAsync();

        return MemberFinancialsActionResult.Ok(effectivePercent);
    }
}

public class VacationFinancialsDto
{
    public decimal MonthlySalary { get; set; }
    public decimal ClientHourlyRate { get; set; }
    public decimal VacationReservePercent { get; set; }
    public bool IsReservePercentManual { get; set; }
    public int VacationDaysPerYear { get; set; }
    public string Currency { get; set; } = string.Empty;
}

public class VacationBalanceDto
{
    public decimal? ReserveBalance { get; set; }
    public int AvailableDays { get; set; }
    public int UsedDays { get; set; }
    public int PendingDays { get; set; }
    public int TotalDaysPerYear { get; set; }
}

public class VacationTransactionDto
{
    public Guid Id { get; set; }
    public string Type { get; set; } = string.Empty;
    public decimal Amount { get; set; }
    public int? BillingPeriodMonth { get; set; }
    public int? BillingPeriodYear { get; set; }
    public string? Description { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
    public Guid? CreatedByAccountId { get; set; }
}

public class VacationRequestDto
{
    public Guid Id { get; set; }
    public DateOnly StartDate { get; set; }
    public DateOnly EndDate { get; set; }
    public int WorkingDays { get; set; }
    public decimal DeductionAmount { get; set; }
    public string Status { get; set; } = string.Empty;
    public DateTime RequestedAt { get; set; }
    public DateTime? ReviewedAt { get; set; }
    public Guid? ReviewedByAccountId { get; set; }
    public string? ReviewerComment { get; set; }
    public DateTime? CancelledAt { get; set; }
    public Guid? CancelledByAccountId { get; set; }
    public bool IsOwnRequest { get; set; }
}

public class VacationDto
{
    public VacationFinancialsDto? Financials { get; set; }
    public VacationBalanceDto? Balance { get; set; }
    public List<VacationRequestDto> Requests { get; set; } = new();
    public List<VacationTransactionDto>? Transactions { get; set; }
    public bool CanEdit { get; set; }
    public bool CanReviewRequests { get; set; }
    public bool CanSubmitRequest { get; set; }
}

public enum VacationFetchOutcome
{
    Success,
    NotFound,
    Forbidden,
}

public class VacationFetchResult
{
    public VacationFetchOutcome Outcome { get; init; }
    public VacationDto? Dto { get; init; }
    public string? ErrorMessage { get; init; }

    public static VacationFetchResult Ok(VacationDto dto) => new() { Outcome = VacationFetchOutcome.Success, Dto = dto };
    public static VacationFetchResult NotFound() => new() { Outcome = VacationFetchOutcome.NotFound };
    public static VacationFetchResult Forbidden(string message) => new()
    { Outcome = VacationFetchOutcome.Forbidden, ErrorMessage = message };
}

public enum MemberFinancialsActionOutcome
{
    Success,
    NotFound,
    Forbidden,
    BadRequest,
    FieldValidation,
}

public class MemberFinancialsActionResult
{
    public MemberFinancialsActionOutcome Outcome { get; init; }
    public string? ErrorCode { get; init; }
    public string? ErrorMessage { get; init; }
    public Dictionary<string, string>? FieldErrors { get; init; }
    public decimal VacationReservePercent { get; init; }

    public static MemberFinancialsActionResult Ok(decimal vacationReservePercent) => new()
    { Outcome = MemberFinancialsActionOutcome.Success, VacationReservePercent = vacationReservePercent };
    public static MemberFinancialsActionResult NotFound() => new() { Outcome = MemberFinancialsActionOutcome.NotFound };
    public static MemberFinancialsActionResult Forbidden(string message, string code = "forbidden") => new()
    { Outcome = MemberFinancialsActionOutcome.Forbidden, ErrorCode = code, ErrorMessage = message };
    public static MemberFinancialsActionResult BadRequest(string code, string message) => new()
    { Outcome = MemberFinancialsActionOutcome.BadRequest, ErrorCode = code, ErrorMessage = message };
    public static MemberFinancialsActionResult FieldValidationError(Dictionary<string, string> errors) => new()
    { Outcome = MemberFinancialsActionOutcome.FieldValidation, FieldErrors = errors };
}
