using Devscribed.Admin.Web.Data;
using Devscribed.Admin.Web.Models;
using Microsoft.EntityFrameworkCore;

namespace Devscribed.Admin.Web.Services;

/// <summary>
/// Generic append-only ledger operations for the vacation reserve. Credit/expiry are posted here (spec 08);
/// spec 09 reuses <see cref="PostTransactionAsync"/> to post debit/refund transactions for vacation requests.
/// </summary>
public class VacationLedgerService
{
    private readonly AppDbContext _db;

    public VacationLedgerService(AppDbContext db)
    {
        _db = db;
    }

    public VacationReserveTransaction PostTransaction(
        Guid membershipId,
        string type,
        decimal amount,
        string? description,
        bool isAutoGenerated,
        Guid? createdByAccountId = null,
        Guid? vacationRequestId = null,
        int? billingPeriodMonth = null,
        int? billingPeriodYear = null,
        DateTime? createdAt = null)
    {
        var transaction = new VacationReserveTransaction
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            Type = type,
            Amount = amount,
            BillingPeriodMonth = billingPeriodMonth,
            BillingPeriodYear = billingPeriodYear,
            Description = description,
            VacationRequestId = vacationRequestId,
            IsAutoGenerated = isAutoGenerated,
            CreatedAt = createdAt ?? DateTime.UtcNow,
            CreatedByAccountId = createdByAccountId,
        };

        _db.VacationReserveTransactions.Add(transaction);
        return transaction;
    }

    /// <summary>
    /// Zeroes out any remaining reserve balance from prior calendar years with an `expiry` transaction.
    /// Callable on its own (e.g. from the year-end background job, spec 09's pending-request cancellation flow,
    /// or opportunistically the first time an admin/manager views the Vacation tab in a new year).
    /// Idempotent: a year that already has an expiry transaction is left untouched.
    /// </summary>
    public async Task EnsureYearEndExpiryAsync(Guid membershipId)
    {
        var currentYear = DateTime.UtcNow.Year;

        var yearsWithActivity = await _db.VacationReserveTransactions
            .Where(t => t.MembershipId == membershipId && t.CreatedAt.Year < currentYear)
            .Select(t => t.CreatedAt.Year)
            .Distinct()
            .ToListAsync();

        var yearsAlreadyExpired = await _db.VacationReserveTransactions
            .Where(t => t.MembershipId == membershipId && t.Type == VacationTransactionTypes.Expiry && t.CreatedAt.Year < currentYear)
            .Select(t => t.CreatedAt.Year)
            .ToListAsync();

        var yearsToExpire = yearsWithActivity.Except(yearsAlreadyExpired).OrderBy(y => y);

        foreach (var year in yearsToExpire)
        {
            // Pending requests that fall within the expired year are auto-cancelled. Any request that was
            // somehow still `approved` past year-end also gets a compensating refund before the balance expires.
            var staleRequests = await _db.VacationRequests
                .Where(r => r.MembershipId == membershipId
                            && r.StartDate.Year == year
                            && (r.Status == VacationRequestStatuses.Pending || r.Status == VacationRequestStatuses.Approved))
                .ToListAsync();

            var refundedThisYear = 0m;
            foreach (var request in staleRequests)
            {
                if (request.Status == VacationRequestStatuses.Approved)
                {
                    PostTransaction(
                        membershipId,
                        VacationTransactionTypes.Refund,
                        amount: request.DeductionAmount,
                        description: $"Refund: vacation cancelled at {year} year-end expiry",
                        isAutoGenerated: true,
                        vacationRequestId: request.Id,
                        createdAt: new DateTime(year, 12, 31, 0, 0, 0, DateTimeKind.Utc));
                    refundedThisYear += request.DeductionAmount;
                }

                request.Status = VacationRequestStatuses.Cancelled;
                request.CancelledAt = new DateTime(year, 12, 31, 0, 0, 0, DateTimeKind.Utc);
            }

            var remainingBalance = await _db.VacationReserveTransactions
                .Where(t => t.MembershipId == membershipId && t.CreatedAt.Year == year)
                .SumAsync(t => t.Amount) + refundedThisYear;

            if (remainingBalance != 0m)
            {
                PostTransaction(
                    membershipId,
                    VacationTransactionTypes.Expiry,
                    amount: -remainingBalance,
                    description: $"{year} year-end expiry",
                    isAutoGenerated: false,
                    createdAt: new DateTime(year, 12, 31, 0, 0, 0, DateTimeKind.Utc));
            }
        }

        await _db.SaveChangesAsync();
    }
}
