namespace Devscribed.Admin.Web.Models;

public static class VacationTransactionTypes
{
    public const string Credit = "credit";
    public const string Expiry = "expiry";
    public const string Debit = "debit";
    public const string Refund = "refund";
}

public class VacationReserveTransaction
{
    public Guid Id { get; set; }
    public Guid MembershipId { get; set; }
    public string Type { get; set; } = string.Empty;
    public decimal Amount { get; set; }
    public int? BillingPeriodMonth { get; set; }
    public int? BillingPeriodYear { get; set; }
    public string? Description { get; set; }
    public Guid? VacationRequestId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
    public Guid? CreatedByAccountId { get; set; }

    public Membership Membership { get; set; } = null!;
}
