# Non-secret dev inputs.
#
# This file holds only what genuinely DIFFERS from prod. Everything about the shape of the
# environment — instance sizes, task sizes, scaling targets, ports, token lifetimes — has
# its value in variables.tf so that it cannot drift between the two: a value that appears
# in both tfvars files is a value someone can edit in one of them by accident.
#
# NO SECRET IS EVER WRITTEN HERE. The session secret, the internal task secret, and the
# database password are generated by Terraform and stored as SecureString parameters; no
# human ever sees any of them.

env = "dev"

vpc_cidr = "10.10.0.0/16"

# Object Lock off. Locked dev objects cannot be cleaned up, which makes the environment
# unusable within weeks.
object_lock_years = 0

# A dev environment may be destroyed. A prod one may not.
bucket_force_destroy   = true
db_deletion_protection = false
db_skip_final_snapshot = true

# ---------------------------------------------------------------------------------------
# Mail
#
# An address rather than a domain, because this account owns no domain. While the account
# is in the SES sandbox — which it is — mail is delivered ONLY to addresses in
# `verified_emails`, and each one has to click a confirmation link AWS sends it. A signer
# whose address is not on this list never receives their invitation.
#
# Add testers here. Leaving the sandbox is a support request with lead time.
# ---------------------------------------------------------------------------------------

sender_email = "ivan.demchenko.dev@gmail.com"

verified_emails = [
  "ivan.demchenko.dev@gmail.com",
]

ses_sandbox_expected = true

# ---------------------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------------------

alarm_email = "ivan.demchenko.dev@gmail.com"

log_retention_days = 14

# The E2E fixtures are open here. Mail is simulated rather than sent — the product has no
# provider yet, and the signing link lives only inside the message — and the suite can move
# a person into an organization, set their role, and age an envelope, none of which the
# product itself can do yet. Without them the deployed suite cannot reach a signing link at
# all, and a third of it cannot build its preconditions.
#
# Costs, stated so nobody has to rediscover them: this environment no longer exercises SES,
# the API is pinned to one task (the outbox is in process memory), and whoever holds
# /devscribed-dev/TEST_FIXTURE_SECRET can read every signing link this stand has issued.
# Turn it off the day real mail works and spec 04 lands.
test_fixtures_enabled = true

# ---------------------------------------------------------------------------------------
# SignWell — documents spec 04
# ---------------------------------------------------------------------------------------

# The sandbox branding profile, so a counterparty signing our contract sees our colours and
# logo rather than SignWell's default. Empty until one is created in the sandbox SignWell
# account; while it is empty the provider stays listed and disabled with "API application
# id" among the missing items.
signwell_api_application_id = "cf61942b-7932-49dc-9975-549464382e7e"

# The two secrets the app module creates parameters for and never values. Flip this to true
# only after both have been written out of band, against the sandbox account:
#
#   aws ssm put-parameter --type SecureString --overwrite --value '<the key>' --name /devscribed-dev/SIGNWELL_API_KEY
#   aws ssm put-parameter --type SecureString --overwrite --value '<the webhook id>' --name /devscribed-dev/SIGNWELL_WEBHOOK_SECRET
#
# Until then the API is handed neither, which is the honest state and one the product is
# built for: the SignWell row on the settings screen is visible, disabled, and names what
# is absent. Nothing else about the environment depends on it — every organization keeps
# signing with the in-house engine, which is what they default to anyway.
#
# The webhook id comes from a registration made by hand, and there is a real obstacle in
# front of it: neither stand has a public address SignWell can reach yet. That costs
# timeliness and not correctness — reads and the hourly sweep converge the same rows — but
# it is why this cannot be provisioned from here.
signwell_secrets_provisioned = true

# ---------------------------------------------------------------------------------------
# CI/CD — provisioned, and off by default. See .github/workflows/deploy.yml.
# ---------------------------------------------------------------------------------------

# There is exactly one GitHub OIDC provider per AWS account, and dev is applied first, so
# dev creates it. prod points at the same one.
create_github_oidc_provider = true

# `environment:dev`, not a branch. The OIDC subject claim takes the `environment:` form
# whenever a workflow job declares an environment — and deploy.yml always does, precisely so
# that the same trust policy shape works for prod, where GitHub's required reviewers attach
# to the environment.
#
# Add a branch form here (`ref:refs/heads/some-branch`) only if you also remove the
# `environment:` declaration from the job, and remember that every ref on this list is a ref
# that can push an image into this account.
github_allowed_refs = [
  "environment:dev",
]

# Hiring keeps CVs on the task's own filesystem and books interviews against the fake
# calendar: CVs survive only until the task is replaced, and bookings invite nobody. Accepted
# on this stand until S3 storage and a Graph tenant exist.
hiring_storage_provider = "fs"
hiring_storage_fs_root  = "/tmp/cv-storage"
calendar_provider       = "fake"
