# Non-secret dev inputs.
#
# This file holds only what genuinely DIFFERS from prod. Everything about the shape of the
# environment — instance sizes, task sizes, scaling targets, ports, token lifetimes — has
# its value in variables.tf so that it cannot drift between the two: a value that appears
# in both tfvars files is a value someone can edit in one of them by accident.
#
# NO SECRET IS EVER WRITTEN HERE. The session secret, the internal task secret, and the
# database password are generated by Terraform and stored as SecureString parameters; no
# human ever sees any of them.

env = "dev"

vpc_cidr = "10.10.0.0/16"

# Object Lock off. Locked dev objects cannot be cleaned up, which makes the environment
# unusable within weeks.
object_lock_years = 0

# A dev environment may be destroyed. A prod one may not.
bucket_force_destroy   = true
db_deletion_protection = false
db_skip_final_snapshot = true

# ---------------------------------------------------------------------------------------
# Mail
#
# An address rather than a domain, because this account owns no domain. While the account
# is in the SES sandbox — which it is — mail is delivered ONLY to addresses in
# `verified_emails`, and each one has to click a confirmation link AWS sends it. A signer
# whose address is not on this list never receives their invitation.
#
# Add testers here. Leaving the sandbox is a support request with lead time.
# ---------------------------------------------------------------------------------------

sender_email = "ivan.demchenko.dev@gmail.com"

verified_emails = [
  "ivan.demchenko.dev@gmail.com",
]

ses_sandbox_expected = true

# ---------------------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------------------

alarm_email = "ivan.demchenko.dev@gmail.com"

log_retention_days = 14

# ---------------------------------------------------------------------------------------
# CI/CD — provisioned, and off by default. See .github/workflows/deploy.yml.
# ---------------------------------------------------------------------------------------

# There is exactly one GitHub OIDC provider per AWS account, and dev is applied first, so
# dev creates it. prod points at the same one.
create_github_oidc_provider = true

# `environment:dev`, not a branch. The OIDC subject claim takes the `environment:` form
# whenever a workflow job declares an environment — and deploy.yml always does, precisely so
# that the same trust policy shape works for prod, where GitHub's required reviewers attach
# to the environment.
#
# Add a branch form here (`ref:refs/heads/some-branch`) only if you also remove the
# `environment:` declaration from the job, and remember that every ref on this list is a ref
# that can push an image into this account.
github_allowed_refs = [
  "environment:dev",
]
