using Devscribed.Admin.Web.Models;
using Devscribed.Admin.Web.Security;
using Devscribed.Admin.Web.Services;
using Devscribed.Admin.Web.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Devscribed.Admin.Web.Controllers.Api;

[ApiController]
[Route("api/organizations/{orgId}/members/{memberId}/vacation")]
[Authorize]
public class VacationController : ControllerBase
{
    private readonly VacationService _vacationService;
    private readonly VacationRequestService _vacationRequestService;

    public VacationController(VacationService vacationService, VacationRequestService vacationRequestService)
    {
        _vacationService = vacationService;
        _vacationRequestService = vacationRequestService;
    }

    [HttpGet]
    public async Task<IActionResult> Get(Guid orgId, Guid memberId)
    {
        if (!TryGetCallerContext(orgId, out _, out var callerMembershipId, out var callerRole, out var errorResult))
            return errorResult!;

        var result = await _vacationService.GetVacationAsync(orgId, memberId, callerMembershipId, callerRole);
        return result.Outcome switch
        {
            VacationFetchOutcome.Success => Ok(new
            {
                financials = result.Dto!.Financials == null ? null : new
                {
                    monthlySalary = result.Dto.Financials.MonthlySalary,
                    clientHourlyRate = result.Dto.Financials.ClientHourlyRate,
                    vacationReservePercent = result.Dto.Financials.VacationReservePercent,
                    isReservePercentManual = result.Dto.Financials.IsReservePercentManual,
                    vacationDaysPerYear = result.Dto.Financials.VacationDaysPerYear,
                    currency = result.Dto.Financials.Currency,
                },
                balance = result.Dto.Balance == null ? null : new
                {
                    reserveBalance = result.Dto.Balance.ReserveBalance,
                    availableDays = result.Dto.Balance.AvailableDays,
                    usedDays = result.Dto.Balance.UsedDays,
                    pendingDays = result.Dto.Balance.PendingDays,
                    totalDaysPerYear = result.Dto.Balance.TotalDaysPerYear,
                },
                requests = result.Dto.Requests.Select(r => new
                {
                    id = r.Id,
                    startDate = r.StartDate,
                    endDate = r.EndDate,
                    workingDays = r.WorkingDays,
                    deductionAmount = r.DeductionAmount,
                    status = r.Status,
                    requestedAt = r.RequestedAt,
                    reviewedAt = r.ReviewedAt,
                    reviewedBy = (string?)null,
                    reviewerComment = r.ReviewerComment,
                    cancelledAt = r.CancelledAt,
                    cancelledBy = (string?)null,
                    isOwnRequest = r.IsOwnRequest,
                }),
                transactions = result.Dto.Transactions?.Select(t => new
                {
                    id = t.Id,
                    type = t.Type,
                    amount = t.Amount,
                    billingPeriodMonth = t.BillingPeriodMonth,
                    billingPeriodYear = t.BillingPeriodYear,
                    description = t.Description,
                    isAutoGenerated = t.IsAutoGenerated,
                    createdAt = t.CreatedAt,
                    createdBy = (string?)null,
                }),
                canEdit = result.Dto.CanEdit,
                canReviewRequests = result.Dto.CanReviewRequests,
                canSubmitRequest = result.Dto.CanSubmitRequest,
            }),
            VacationFetchOutcome.NotFound => NotFound(new { error = "not_found", message = "Member not found" }),
            VacationFetchOutcome.Forbidden => StatusCode(403, new { error = "forbidden", message = result.ErrorMessage }),
            _ => StatusCode(500),
        };
    }

    [HttpPut("financials")]
    public async Task<IActionResult> UpdateFinancials(Guid orgId, Guid memberId, [FromBody] UpdateMemberFinancialsRequest request)
    {
        if (!TryGetCallerContext(orgId, out var callerAccountId, out _, out var callerRole, out var errorResult))
            return errorResult!;

        var result = await _vacationService.UpdateFinancialsAsync(orgId, memberId, callerAccountId, callerRole, request);
        return MapResult(result);
    }

    [HttpPost("requests")]
    public async Task<IActionResult> SubmitRequest(Guid orgId, Guid memberId, [FromBody] SubmitVacationRequest request)
    {
        if (!TryGetCallerContext(orgId, out _, out var callerMembershipId, out var callerRole, out var errorResult))
            return errorResult!;

        if (request.StartDate == null || request.EndDate == null)
        {
            var errors = new Dictionary<string, string>();
            if (request.StartDate == null) errors["startDate"] = "Start date must be today or later";
            if (request.EndDate == null) errors["endDate"] = "End date must be on or after start date";
            return BadRequest(new { errors });
        }

        var result = await _vacationRequestService.SubmitRequestAsync(
            orgId, memberId, callerMembershipId, callerRole, request.StartDate.Value, request.EndDate.Value);

        return result.Outcome switch
        {
            VacationRequestActionOutcome.Created => StatusCode(201, new
            {
                id = result.Request!.Id,
                workingDays = result.Request.WorkingDays,
                deductionAmount = result.Request.DeductionAmount,
                status = result.Request.Status,
            }),
            VacationRequestActionOutcome.NotFound => NotFound(new { error = "not_found", message = "Member not found" }),
            VacationRequestActionOutcome.Forbidden => StatusCode(403, new { error = result.ErrorCode ?? "forbidden", message = result.ErrorMessage }),
            VacationRequestActionOutcome.BadRequest => BadRequest(new { error = result.ErrorCode, message = result.ErrorMessage }),
            VacationRequestActionOutcome.FieldValidation => BadRequest(new { errors = result.FieldErrors }),
            _ => StatusCode(500),
        };
    }

    [HttpPut("requests/{requestId}/review")]
    public async Task<IActionResult> ReviewRequest(Guid orgId, Guid memberId, Guid requestId, [FromBody] ReviewVacationRequest request)
    {
        if (!TryGetCallerContext(orgId, out var callerAccountId, out var callerMembershipId, out var callerRole, out var errorResult))
            return errorResult!;

        var result = await _vacationRequestService.ReviewRequestAsync(
            orgId, memberId, requestId, callerMembershipId, callerAccountId, callerRole, request.Decision ?? string.Empty, request.Comment);

        return result.Outcome switch
        {
            VacationRequestActionOutcome.Reviewed => Ok(new { success = true, status = result.Status }),
            VacationRequestActionOutcome.NotFound => NotFound(new { error = "not_found", message = "Request not found" }),
            VacationRequestActionOutcome.Forbidden => StatusCode(403, new { error = result.ErrorCode ?? "forbidden", message = result.ErrorMessage }),
            VacationRequestActionOutcome.BadRequest => BadRequest(new { error = result.ErrorCode, message = result.ErrorMessage }),
            VacationRequestActionOutcome.FieldValidation => BadRequest(new { errors = result.FieldErrors }),
            _ => StatusCode(500),
        };
    }

    [HttpPut("requests/{requestId}/cancel")]
    public async Task<IActionResult> CancelRequest(Guid orgId, Guid memberId, Guid requestId)
    {
        if (!TryGetCallerContext(orgId, out var callerAccountId, out var callerMembershipId, out var callerRole, out var errorResult))
            return errorResult!;

        var result = await _vacationRequestService.CancelRequestAsync(
            orgId, memberId, requestId, callerMembershipId, callerAccountId, callerRole);

        return result.Outcome switch
        {
            VacationRequestActionOutcome.Cancelled => Ok(new { success = true, refunded = result.Refunded, refundAmount = result.RefundAmount }),
            VacationRequestActionOutcome.NotFound => NotFound(new { error = "not_found", message = "Request not found" }),
            VacationRequestActionOutcome.Forbidden => StatusCode(403, new { error = result.ErrorCode ?? "forbidden", message = result.ErrorMessage }),
            VacationRequestActionOutcome.BadRequest => BadRequest(new { error = result.ErrorCode, message = result.ErrorMessage }),
            _ => StatusCode(500),
        };
    }

    private bool TryGetCallerContext(Guid orgId, out Guid callerAccountId, out Guid callerMembershipId, out string callerRole, out IActionResult? errorResult)
    {
        callerAccountId = Guid.Empty;
        callerMembershipId = Guid.Empty;
        callerRole = string.Empty;
        errorResult = null;

        var orgIdClaim = User.FindFirstValue(AppClaimTypes.OrganizationId);
        var accountIdClaim = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var membershipIdClaim = User.FindFirstValue(AppClaimTypes.MembershipId);
        var role = User.FindFirstValue(ClaimTypes.Role);

        if (orgIdClaim == null || !Guid.TryParse(orgIdClaim, out var callerOrgId)
            || accountIdClaim == null || !Guid.TryParse(accountIdClaim, out var accountId)
            || membershipIdClaim == null || !Guid.TryParse(membershipIdClaim, out var membershipId)
            || role == null)
        {
            errorResult = Unauthorized();
            return false;
        }

        if (callerOrgId != orgId)
        {
            errorResult = Forbid();
            return false;
        }

        callerAccountId = accountId;
        callerMembershipId = membershipId;
        callerRole = role;
        return true;
    }

    private IActionResult MapResult(MemberFinancialsActionResult result)
    {
        return result.Outcome switch
        {
            MemberFinancialsActionOutcome.Success => Ok(new { success = true, vacationReservePercent = result.VacationReservePercent }),
            MemberFinancialsActionOutcome.NotFound => NotFound(new { error = "not_found", message = "Member not found" }),
            MemberFinancialsActionOutcome.Forbidden => StatusCode(403, new { error = result.ErrorCode ?? "forbidden", message = result.ErrorMessage }),
            MemberFinancialsActionOutcome.BadRequest => BadRequest(new { error = result.ErrorCode, message = result.ErrorMessage }),
            MemberFinancialsActionOutcome.FieldValidation => BadRequest(new { errors = result.FieldErrors }),
            _ => StatusCode(500),
        };
    }
}
