using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Devscribed.Admin.Web.Data;
using Devscribed.Admin.Web.Models;
using Devscribed.Admin.Web.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Devscribed.Admin.Tests.Integration;

public class OrganizationRequestsIntegrationTests : IClassFixture<TestWebAppFactory>
{
    private readonly TestWebAppFactory _factory;

    public OrganizationRequestsIntegrationTests(TestWebAppFactory factory)
    {
        _factory = factory;
    }

    private async Task<(Account Account, Membership Membership)> SeedMemberAsync(
        Organization org, string email, string password, string role = "user", string status = "active",
        string firstName = "Pat", string lastName = "Owner")
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var hasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher>();

        if (!db.Organizations.Any(o => o.Id == org.Id))
            db.Organizations.Add(org);

        var account = new Account
        {
            Id = Guid.NewGuid(),
            Email = email,
            PasswordHash = hasher.Hash(password),
            FirstName = firstName,
            LastName = lastName,
            CreatedAt = DateTime.UtcNow,
        };
        var membership = new Membership
        {
            Id = Guid.NewGuid(),
            AccountId = account.Id,
            OrganizationId = org.Id,
            Role = role,
            Status = status,
            JoinedAt = DateTime.UtcNow,
        };
        db.Accounts.Add(account);
        db.Memberships.Add(membership);
        await db.SaveChangesAsync();
        return (account, membership);
    }

    private static Organization NewOrg(string name) => new() { Id = Guid.NewGuid(), Name = name, CreatedAt = DateTime.UtcNow };

    private async Task<HttpClient> LoggedInClientAsync(string email, string password)
    {
        var client = _factory.CreateClient();
        var response = await client.PostAsJsonAsync("/api/login", new { email, password });
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        return client;
    }

    private async Task SetFinancialsAsync(Guid membershipId, decimal monthlySalary, int vacationDaysPerYear = 20)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        db.MemberFinancials.Add(new MemberFinancials
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            MonthlySalary = monthlySalary,
            ClientHourlyRate = 40m,
            VacationDaysPerYear = vacationDaysPerYear,
            Currency = "USD",
            VacationReservePercent = 3.33m,
            UpdatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();
    }

    private async Task AddCreditAsync(Guid membershipId, decimal amount)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var ledger = scope.ServiceProvider.GetRequiredService<VacationLedgerService>();
        ledger.PostTransaction(membershipId, VacationTransactionTypes.Credit, amount, "seed credit", isAutoGenerated: true);
        await db.SaveChangesAsync();
    }

    private async Task<VacationRequest> SeedRequestAsync(
        Guid membershipId, DateOnly start, DateOnly end, int workingDays, decimal deductionAmount, string status, DateTime? requestedAt = null)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var request = new VacationRequest
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            StartDate = start,
            EndDate = end,
            WorkingDays = workingDays,
            DeductionAmount = deductionAmount,
            Status = status,
            RequestedAt = requestedAt ?? DateTime.UtcNow,
        };
        if (status is VacationRequestStatuses.Approved or VacationRequestStatuses.Rejected or VacationRequestStatuses.Cancelled)
            request.ReviewedAt = DateTime.UtcNow;

        db.VacationRequests.Add(request);
        await db.SaveChangesAsync();
        return request;
    }

    private static DateOnly FutureMonday(int weeksAhead)
    {
        var today = DateTime.UtcNow.Date;
        var daysUntilMonday = ((int)DayOfWeek.Monday - (int)today.DayOfWeek + 7) % 7;
        if (daysUntilMonday == 0) daysUntilMonday = 7;
        return DateOnly.FromDateTime(today.AddDays(daysUntilMonday + weeksAhead * 7));
    }

    private const decimal MonthlySalaryFor10Days = 3000m;

    // TC-10-INT-01: Requests page — returns pending requests for all org members
    [Fact]
    public async Task Returns_pending_requests_across_all_org_members()
    {
        var org = NewOrg("Acme Inc");
        await SeedMemberAsync(org, "admin10-01@acme.com", "Passw0rd", role: "admin");
        var (_, m1) = await SeedMemberAsync(org, "m1-10-01@acme.com", "Passw0rd", role: "user");
        var (_, m2) = await SeedMemberAsync(org, "m2-10-01@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(m1.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(m1.Id, 5000m);
        await SetFinancialsAsync(m2.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(m2.Id, 5000m);

        await SeedRequestAsync(m1.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);
        await SeedRequestAsync(m2.Id, FutureMonday(2), FutureMonday(2).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);
        await SeedRequestAsync(m2.Id, FutureMonday(3), FutureMonday(3).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        var client = await LoggedInClientAsync("admin10-01@acme.com", "Passw0rd");
        var response = await client.GetAsync($"/api/organizations/{org.Id}/requests?status=pending");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        var requests = body.GetProperty("requests").EnumerateArray().ToList();
        Assert.Equal(3, requests.Count);
        Assert.Equal(3, body.GetProperty("pendingCount").GetInt32());

        var first = requests[0];
        Assert.Equal("vacation", first.GetProperty("type").GetString());
        Assert.True(first.GetProperty("member").GetProperty("membershipId").GetGuid() != Guid.Empty);
        Assert.False(string.IsNullOrEmpty(first.GetProperty("member").GetProperty("firstName").GetString()));
        Assert.False(string.IsNullOrEmpty(first.GetProperty("member").GetProperty("initials").GetString()));
        Assert.Equal(20, first.GetProperty("memberBalance").GetProperty("availableDays").GetInt32());
    }

    // TC-10-INT-02: Requests page — status filter
    [Fact]
    public async Task Status_filter_returns_correct_subset()
    {
        var org = NewOrg("Acme Inc");
        await SeedMemberAsync(org, "admin10-02@acme.com", "Passw0rd", role: "admin");
        var (_, m) = await SeedMemberAsync(org, "m10-02@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(m.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(m.Id, 5000m);

        await SeedRequestAsync(m.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);
        await SeedRequestAsync(m.Id, FutureMonday(2), FutureMonday(2).AddDays(4), 5, 692.31m, VacationRequestStatuses.Approved);
        await SeedRequestAsync(m.Id, FutureMonday(3), FutureMonday(3).AddDays(4), 5, 692.31m, VacationRequestStatuses.Rejected);

        var client = await LoggedInClientAsync("admin10-02@acme.com", "Passw0rd");

        var allResponse = await client.GetAsync($"/api/organizations/{org.Id}/requests?status=all");
        var allBody = (await allResponse.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal(3, allBody.GetProperty("requests").GetArrayLength());

        var approvedResponse = await client.GetAsync($"/api/organizations/{org.Id}/requests?status=approved");
        var approvedBody = (await approvedResponse.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal(1, approvedBody.GetProperty("requests").GetArrayLength());

        var pendingResponse = await client.GetAsync($"/api/organizations/{org.Id}/requests?status=pending");
        var pendingBody = (await pendingResponse.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal(1, pendingBody.GetProperty("requests").GetArrayLength());
    }

    // TC-10-INT-03: Requests page — forbidden for user/viewer
    [Fact]
    public async Task Forbidden_for_user_and_viewer()
    {
        var org = NewOrg("Acme Inc");
        await SeedMemberAsync(org, "admin10-03@acme.com", "Passw0rd", role: "admin");
        await SeedMemberAsync(org, "user10-03@acme.com", "Passw0rd", role: "user");
        await SeedMemberAsync(org, "viewer10-03@acme.com", "Passw0rd", role: "viewer");

        var userClient = await LoggedInClientAsync("user10-03@acme.com", "Passw0rd");
        var userResponse = await userClient.GetAsync($"/api/organizations/{org.Id}/requests");
        Assert.Equal(HttpStatusCode.Forbidden, userResponse.StatusCode);
        var userBody = (await userResponse.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("forbidden", userBody.GetProperty("error").GetString());

        var viewerClient = await LoggedInClientAsync("viewer10-03@acme.com", "Passw0rd");
        var viewerResponse = await viewerClient.GetAsync($"/api/organizations/{org.Id}/requests");
        Assert.Equal(HttpStatusCode.Forbidden, viewerResponse.StatusCode);
    }

    // Sorting: pending oldest-first, others newest-first
    [Fact]
    public async Task Sorting_matches_spec_pending_oldest_others_newest()
    {
        var org = NewOrg("Acme Inc");
        await SeedMemberAsync(org, "admin10-04@acme.com", "Passw0rd", role: "admin");
        var (_, m) = await SeedMemberAsync(org, "m10-04@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(m.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(m.Id, 5000m);

        var now = DateTime.UtcNow;
        var p1 = await SeedRequestAsync(m.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending, now.AddDays(-5));
        var p2 = await SeedRequestAsync(m.Id, FutureMonday(2), FutureMonday(2).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending, now.AddDays(-1));
        var a1 = await SeedRequestAsync(m.Id, FutureMonday(3), FutureMonday(3).AddDays(4), 5, 692.31m, VacationRequestStatuses.Approved, now.AddDays(-10));
        var a2 = await SeedRequestAsync(m.Id, FutureMonday(4), FutureMonday(4).AddDays(4), 5, 692.31m, VacationRequestStatuses.Approved, now.AddDays(-2));

        var client = await LoggedInClientAsync("admin10-04@acme.com", "Passw0rd");
        var response = await client.GetAsync($"/api/organizations/{org.Id}/requests?status=all");
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        var ids = body.GetProperty("requests").EnumerateArray().Select(r => r.GetProperty("id").GetGuid()).ToList();

        Assert.Equal(new[] { p1.Id, p2.Id, a2.Id, a1.Id }, ids);
    }
}
