using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Devscribed.Admin.Web.Data;
using Devscribed.Admin.Web.Models;
using Devscribed.Admin.Web.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Devscribed.Admin.Tests.Integration;

public class VacationRequestsIntegrationTests : IClassFixture<TestWebAppFactory>
{
    private readonly TestWebAppFactory _factory;

    public VacationRequestsIntegrationTests(TestWebAppFactory factory)
    {
        _factory = factory;
    }

    private async Task<(Account Account, Membership Membership)> SeedMemberAsync(
        Organization org, string email, string password, string role = "user", string status = "active",
        string firstName = "Pat", string lastName = "Owner")
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var hasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher>();

        if (!db.Organizations.Any(o => o.Id == org.Id))
            db.Organizations.Add(org);

        var account = new Account
        {
            Id = Guid.NewGuid(),
            Email = email,
            PasswordHash = hasher.Hash(password),
            FirstName = firstName,
            LastName = lastName,
            CreatedAt = DateTime.UtcNow,
        };
        var membership = new Membership
        {
            Id = Guid.NewGuid(),
            AccountId = account.Id,
            OrganizationId = org.Id,
            Role = role,
            Status = status,
            JoinedAt = DateTime.UtcNow,
        };
        db.Accounts.Add(account);
        db.Memberships.Add(membership);
        await db.SaveChangesAsync();
        return (account, membership);
    }

    private static Organization NewOrg(string name) => new() { Id = Guid.NewGuid(), Name = name, CreatedAt = DateTime.UtcNow };

    private async Task<HttpClient> LoggedInClientAsync(string email, string password)
    {
        var client = _factory.CreateClient();
        var response = await client.PostAsJsonAsync("/api/login", new { email, password });
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        return client;
    }

    private async Task SetFinancialsAsync(Guid membershipId, decimal monthlySalary, int vacationDaysPerYear = 20)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        db.MemberFinancials.Add(new MemberFinancials
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            MonthlySalary = monthlySalary,
            ClientHourlyRate = 40m,
            VacationDaysPerYear = vacationDaysPerYear,
            Currency = "USD",
            VacationReservePercent = 3.33m,
            UpdatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();
    }

    private async Task AddCreditAsync(Guid membershipId, decimal amount)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var ledger = scope.ServiceProvider.GetRequiredService<VacationLedgerService>();
        ledger.PostTransaction(membershipId, VacationTransactionTypes.Credit, amount, "seed credit", isAutoGenerated: true);
        await db.SaveChangesAsync();
    }

    private async Task AddDebitAsync(Guid membershipId, Guid requestId, decimal amount)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var ledger = scope.ServiceProvider.GetRequiredService<VacationLedgerService>();
        ledger.PostTransaction(membershipId, VacationTransactionTypes.Debit, -amount, "seed debit", isAutoGenerated: false, vacationRequestId: requestId);
        await db.SaveChangesAsync();
    }

    private async Task<VacationRequest> SeedRequestAsync(
        Guid membershipId, DateOnly start, DateOnly end, int workingDays, decimal deductionAmount, string status)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var request = new VacationRequest
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            StartDate = start,
            EndDate = end,
            WorkingDays = workingDays,
            DeductionAmount = deductionAmount,
            Status = status,
            RequestedAt = DateTime.UtcNow,
        };
        if (status == VacationRequestStatuses.Approved)
        {
            request.ReviewedAt = DateTime.UtcNow;
        }
        db.VacationRequests.Add(request);
        await db.SaveChangesAsync();
        return request;
    }

    // dailySalary for monthlySalary=3000 is 3000*12/260 = 138.4615...
    private const decimal MonthlySalaryFor10Days = 3000m;

    // Returns a future Monday (so Monday..+4 days is always exactly 5 weekdays), offset by whole weeks
    // so test date ranges never overlap with each other and are always relative to "today" regardless of
    // when the suite runs.
    private static DateOnly FutureMonday(int weeksAhead)
    {
        var today = DateTime.UtcNow.Date;
        var daysUntilMonday = ((int)DayOfWeek.Monday - (int)today.DayOfWeek + 7) % 7;
        if (daysUntilMonday == 0) daysUntilMonday = 7;
        return DateOnly.FromDateTime(today.AddDays(daysUntilMonday + weeksAhead * 7));
    }

    // TC-09-INT-01: Submit vacation request — happy path
    [Fact]
    public async Task Submit_request_happy_path_reduces_available_days()
    {
        var org = NewOrg("Acme Inc");
        var (_, user) = await SeedMemberAsync(org, "user01@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 1384.62m); // ~10 days worth

        var start = FutureMonday(1);
        var client = await LoggedInClientAsync("user01@acme.com", "Passw0rd");
        var response = await client.PostAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests",
            new { startDate = start.ToString("yyyy-MM-dd"), endDate = start.AddDays(4).ToString("yyyy-MM-dd") });

        Assert.Equal(HttpStatusCode.Created, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal(5, body.GetProperty("workingDays").GetInt32());
        Assert.Equal("pending", body.GetProperty("status").GetString());

        var getResponse = await client.GetAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation");
        var getBody = (await getResponse.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal(5, getBody.GetProperty("balance").GetProperty("pendingDays").GetInt32());
    }

    // TC-09-INT-02: Submit vacation request — insufficient balance
    [Fact]
    public async Task Submit_request_insufficient_balance_rejected()
    {
        var org = NewOrg("Acme Inc");
        var (_, user) = await SeedMemberAsync(org, "user02@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 276.93m); // ~2 days worth (dailySalary = 138.4615...)

        var start = FutureMonday(1);
        var client = await LoggedInClientAsync("user02@acme.com", "Passw0rd");
        var response = await client.PostAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests",
            new { startDate = start.ToString("yyyy-MM-dd"), endDate = start.AddDays(4).ToString("yyyy-MM-dd") }); // 5 working days

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("insufficient_balance", body.GetProperty("error").GetString());
        Assert.Equal("Insufficient vacation balance. You have 2 day(s) available.", body.GetProperty("message").GetString());
    }

    // TC-09-INT-03: Submit vacation request — overlap
    [Fact]
    public async Task Submit_request_overlap_rejected()
    {
        var org = NewOrg("Acme Inc");
        var (_, user) = await SeedMemberAsync(org, "user03@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 5000m);

        var start = FutureMonday(1);
        var client = await LoggedInClientAsync("user03@acme.com", "Passw0rd");
        await client.PostAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests",
            new { startDate = start.ToString("yyyy-MM-dd"), endDate = start.AddDays(4).ToString("yyyy-MM-dd") });

        var response = await client.PostAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests",
            new { startDate = start.AddDays(2).ToString("yyyy-MM-dd"), endDate = start.AddDays(8).ToString("yyyy-MM-dd") });

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("overlap", body.GetProperty("error").GetString());
    }

    // TC-09-INT-04: Submit vacation request — cross-year
    [Fact]
    public async Task Submit_request_cross_year_rejected()
    {
        var org = NewOrg("Acme Inc");
        var (_, user) = await SeedMemberAsync(org, "user04@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 5000m);

        var year = DateTime.UtcNow.Year + 1;
        var client = await LoggedInClientAsync("user04@acme.com", "Passw0rd");
        var response = await client.PostAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests",
            new { startDate = $"{year}-12-29", endDate = $"{year + 1}-01-02" });

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("cross_year", body.GetProperty("error").GetString());
    }

    // TC-09-INT-05: Submit vacation request — only for own membership
    [Fact]
    public async Task Submit_request_for_another_member_forbidden()
    {
        var org = NewOrg("Acme Inc");
        var (_, u) = await SeedMemberAsync(org, "user05@acme.com", "Passw0rd", role: "user");
        var (_, a) = await SeedMemberAsync(org, "admin05@acme.com", "Passw0rd", role: "admin");
        await SetFinancialsAsync(a.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(a.Id, 5000m);

        var start = FutureMonday(1);
        var client = await LoggedInClientAsync("user05@acme.com", "Passw0rd");
        var response = await client.PostAsJsonAsync($"/api/organizations/{org.Id}/members/{a.Id}/vacation/requests",
            new { startDate = start.ToString("yyyy-MM-dd"), endDate = start.AddDays(4).ToString("yyyy-MM-dd") });

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("forbidden", body.GetProperty("error").GetString());
        Assert.Equal("You can only submit vacation requests for yourself", body.GetProperty("message").GetString());
    }

    // TC-09-INT-06: Approve request — happy path
    [Fact]
    public async Task Approve_request_creates_debit_and_updates_balance()
    {
        var org = NewOrg("Acme Inc");
        await SeedMemberAsync(org, "admin06@acme.com", "Passw0rd", role: "admin");
        var (_, user) = await SeedMemberAsync(org, "user06@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 5000m);
        var request = await SeedRequestAsync(user.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        var client = await LoggedInClientAsync("admin06@acme.com", "Passw0rd");
        var response = await client.PutAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests/{request.Id}/review",
            new { decision = "approved" });

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("approved", body.GetProperty("status").GetString());

        var getResponse = await client.GetAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation");
        var getBody = (await getResponse.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal(5, getBody.GetProperty("balance").GetProperty("usedDays").GetInt32());
        Assert.Equal(0, getBody.GetProperty("balance").GetProperty("pendingDays").GetInt32());
        Assert.Equal(5000m - 692.31m, getBody.GetProperty("balance").GetProperty("reserveBalance").GetDecimal());

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var debit = await db.VacationReserveTransactions.SingleAsync(t => t.VacationRequestId == request.Id && t.Type == "debit");
        Assert.Equal(-692.31m, debit.Amount);
    }

    // TC-09-INT-07: Approve request — self-approval rejected
    [Fact]
    public async Task Approve_request_self_approval_rejected()
    {
        var org = NewOrg("Acme Inc");
        var (_, admin) = await SeedMemberAsync(org, "admin07@acme.com", "Passw0rd", role: "admin");
        await SetFinancialsAsync(admin.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(admin.Id, 5000m);
        var request = await SeedRequestAsync(admin.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        var client = await LoggedInClientAsync("admin07@acme.com", "Passw0rd");
        var response = await client.PutAsJsonAsync($"/api/organizations/{org.Id}/members/{admin.Id}/vacation/requests/{request.Id}/review",
            new { decision = "approved" });

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("self_approval", body.GetProperty("error").GetString());

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var reloaded = await db.VacationRequests.SingleAsync(r => r.Id == request.Id);
        Assert.Equal(VacationRequestStatuses.Pending, reloaded.Status);
    }

    // TC-09-INT-08: Reject request — with comment
    [Fact]
    public async Task Reject_request_with_comment_releases_pending_hold()
    {
        var org = NewOrg("Acme Inc");
        await SeedMemberAsync(org, "admin08@acme.com", "Passw0rd", role: "admin");
        var (_, manager) = await SeedMemberAsync(org, "manager08@acme.com", "Passw0rd", role: "manager");
        var (_, user) = await SeedMemberAsync(org, "user08@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 5000m);
        var request = await SeedRequestAsync(user.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        var client = await LoggedInClientAsync("manager08@acme.com", "Passw0rd");
        var response = await client.PutAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests/{request.Id}/review",
            new { decision = "rejected", comment = "Team capacity" });

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("rejected", body.GetProperty("status").GetString());

        var adminClient = await LoggedInClientAsync("admin08@acme.com", "Passw0rd");
        var getResponse = await adminClient.GetAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation");
        var getBody = (await getResponse.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        var requests = getBody.GetProperty("requests").EnumerateArray().ToList();
        var reqJson = requests.Single(r => r.GetProperty("id").GetGuid() == request.Id);
        Assert.Equal("Team capacity", reqJson.GetProperty("reviewerComment").GetString());
        Assert.Equal(0, getBody.GetProperty("balance").GetProperty("pendingDays").GetInt32());

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        Assert.False(await db.VacationReserveTransactions.AnyAsync(t => t.VacationRequestId == request.Id));
    }

    // TC-09-INT-09: Cancel pending request — by owner
    [Fact]
    public async Task Cancel_pending_request_by_owner_no_refund()
    {
        var org = NewOrg("Acme Inc");
        var (_, user) = await SeedMemberAsync(org, "user09@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 5000m);
        var request = await SeedRequestAsync(user.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        var client = await LoggedInClientAsync("user09@acme.com", "Passw0rd");
        var response = await client.PutAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests/{request.Id}/cancel", null);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.False(body.GetProperty("refunded").GetBoolean());

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var reloaded = await db.VacationRequests.SingleAsync(r => r.Id == request.Id);
        Assert.Equal(VacationRequestStatuses.Cancelled, reloaded.Status);
        Assert.False(await db.VacationReserveTransactions.AnyAsync(t => t.VacationRequestId == request.Id));
    }

    // TC-09-INT-10: Cancel approved request — by manager (refund)
    [Fact]
    public async Task Cancel_approved_request_by_manager_creates_refund()
    {
        var org = NewOrg("Acme Inc");
        var (_, manager) = await SeedMemberAsync(org, "manager10@acme.com", "Passw0rd", role: "manager");
        var (_, user) = await SeedMemberAsync(org, "user10@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 5000m);
        var request = await SeedRequestAsync(user.Id, FutureMonday(3), FutureMonday(3).AddDays(4), 5, 692.31m, VacationRequestStatuses.Approved);
        await AddDebitAsync(user.Id, request.Id, 692.31m); // simulate the debit that a real approval would have posted

        var client = await LoggedInClientAsync("manager10@acme.com", "Passw0rd");
        var response = await client.PutAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests/{request.Id}/cancel", null);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.True(body.GetProperty("refunded").GetBoolean());
        Assert.Equal(692.31m, body.GetProperty("refundAmount").GetDecimal());

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var reloaded = await db.VacationRequests.SingleAsync(r => r.Id == request.Id);
        Assert.Equal(VacationRequestStatuses.Cancelled, reloaded.Status);
        var refund = await db.VacationReserveTransactions.SingleAsync(t => t.VacationRequestId == request.Id && t.Type == "refund");
        Assert.Equal(692.31m, refund.Amount);

        var reserveBalance = await db.VacationReserveTransactions.Where(t => t.MembershipId == user.Id).SumAsync(t => t.Amount);
        Assert.Equal(5000m, reserveBalance); // credit 5000 - debit 692.31 + refund 692.31
    }

    // TC-09-INT-11: Cancel request — user cannot cancel approved request
    [Fact]
    public async Task User_cannot_cancel_own_approved_request()
    {
        var org = NewOrg("Acme Inc");
        var (_, user) = await SeedMemberAsync(org, "user11@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 5000m);
        var request = await SeedRequestAsync(user.Id, FutureMonday(3), FutureMonday(3).AddDays(4), 5, 692.31m, VacationRequestStatuses.Approved);

        var client = await LoggedInClientAsync("user11@acme.com", "Passw0rd");
        var response = await client.PutAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests/{request.Id}/cancel", null);

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("forbidden", body.GetProperty("error").GetString());

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var reloaded = await db.VacationRequests.SingleAsync(r => r.Id == request.Id);
        Assert.Equal(VacationRequestStatuses.Approved, reloaded.Status);
    }

    // TC-09-INT-12: Concurrent approval race condition
    [Fact]
    public async Task Concurrent_approvals_only_one_succeeds()
    {
        var org = NewOrg("Acme Inc");
        var (_, admin) = await SeedMemberAsync(org, "admin12@acme.com", "Passw0rd", role: "admin");
        var (_, manager) = await SeedMemberAsync(org, "manager12@acme.com", "Passw0rd", role: "manager");
        var (_, user) = await SeedMemberAsync(org, "user12@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 692.31m); // exactly ~5 days worth (matches one request)

        var r1 = await SeedRequestAsync(user.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);
        var r2 = await SeedRequestAsync(user.Id, FutureMonday(2), FutureMonday(2).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        var adminClient = await LoggedInClientAsync("admin12@acme.com", "Passw0rd");
        var managerClient = await LoggedInClientAsync("manager12@acme.com", "Passw0rd");

        var task1 = adminClient.PutAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests/{r1.Id}/review", new { decision = "approved" });
        var task2 = managerClient.PutAsJsonAsync($"/api/organizations/{org.Id}/members/{user.Id}/vacation/requests/{r2.Id}/review", new { decision = "approved" });

        var results = await Task.WhenAll(task1, task2);

        var successCount = results.Count(r => r.StatusCode == HttpStatusCode.OK);
        var failureCount = results.Count(r => r.StatusCode == HttpStatusCode.BadRequest);

        Assert.Equal(1, successCount);
        Assert.Equal(1, failureCount);

        var failedResponse = results.First(r => r.StatusCode == HttpStatusCode.BadRequest);
        var failedBody = (await failedResponse.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        Assert.Equal("insufficient_balance", failedBody.GetProperty("error").GetString());

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var debitCount = await db.VacationReserveTransactions.CountAsync(t => t.MembershipId == user.Id && t.Type == "debit");
        Assert.Equal(1, debitCount);
    }

    // TC-09-INT-13: Member removal auto-cancels pending requests
    [Fact]
    public async Task Removing_member_cancels_pending_and_future_approved_requests()
    {
        var org = NewOrg("Acme Inc");
        await SeedMemberAsync(org, "admin13@acme.com", "Passw0rd", role: "admin");
        var (_, user) = await SeedMemberAsync(org, "user13@acme.com", "Passw0rd", role: "user");
        await SetFinancialsAsync(user.Id, MonthlySalaryFor10Days);
        await AddCreditAsync(user.Id, 5000m);

        var futureDate = DateTime.UtcNow.AddMonths(2);
        var r1 = await SeedRequestAsync(user.Id, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);
        var r2 = await SeedRequestAsync(user.Id, DateOnly.FromDateTime(futureDate), DateOnly.FromDateTime(futureDate.AddDays(4)), 5, 692.31m, VacationRequestStatuses.Approved);

        var client = await LoggedInClientAsync("admin13@acme.com", "Passw0rd");
        var response = await client.DeleteAsync($"/api/organizations/{org.Id}/members/{user.Id}");
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var reloadedR1 = await db.VacationRequests.SingleAsync(r => r.Id == r1.Id);
        var reloadedR2 = await db.VacationRequests.SingleAsync(r => r.Id == r2.Id);

        Assert.Equal(VacationRequestStatuses.Cancelled, reloadedR1.Status);
        Assert.Equal(VacationRequestStatuses.Cancelled, reloadedR2.Status);
        var refund = await db.VacationReserveTransactions.SingleOrDefaultAsync(t => t.VacationRequestId == r2.Id && t.Type == "refund");
        Assert.NotNull(refund);
        Assert.Equal(692.31m, refund!.Amount);
        Assert.False(await db.VacationReserveTransactions.AnyAsync(t => t.VacationRequestId == r1.Id));
    }
}
