using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Devscribed.Admin.Web.Data;
using Devscribed.Admin.Web.Models;
using Devscribed.Admin.Web.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Devscribed.Admin.Tests.Integration;

public class VacationYearEndExpiryIntegrationTests : IClassFixture<TestWebAppFactory>
{
    private readonly TestWebAppFactory _factory;

    public VacationYearEndExpiryIntegrationTests(TestWebAppFactory factory)
    {
        _factory = factory;
    }

    private async Task<(Account Account, Membership Membership)> SeedMemberAsync(
        Organization org, string email, string password, string role = "user", string status = "active")
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var hasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher>();

        if (!db.Organizations.Any(o => o.Id == org.Id))
            db.Organizations.Add(org);

        var account = new Account
        {
            Id = Guid.NewGuid(),
            Email = email,
            PasswordHash = hasher.Hash(password),
            FirstName = "Pat",
            LastName = "Owner",
            CreatedAt = DateTime.UtcNow,
        };
        var membership = new Membership
        {
            Id = Guid.NewGuid(),
            AccountId = account.Id,
            OrganizationId = org.Id,
            Role = role,
            Status = status,
            JoinedAt = DateTime.UtcNow,
        };
        db.Accounts.Add(account);
        db.Memberships.Add(membership);
        await db.SaveChangesAsync();
        return (account, membership);
    }

    private static Organization NewOrg(string name) => new() { Id = Guid.NewGuid(), Name = name, CreatedAt = DateTime.UtcNow };

    private async Task<HttpClient> LoggedInClientAsync(string email, string password)
    {
        var client = _factory.CreateClient();
        var response = await client.PostAsJsonAsync("/api/login", new { email, password });
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        return client;
    }

    // Year-end expiry: stale prior-year reserve balance is zeroed by an `expiry` transaction
    // the first time an admin/manager views the Vacation tab.
    [Fact]
    public async Task Viewing_vacation_tab_expires_prior_year_balance()
    {
        var org = NewOrg("Acme Inc");
        await SeedMemberAsync(org, "admin-exp01@acme.com", "Passw0rd", role: "admin");
        var (_, target) = await SeedMemberAsync(org, "target-exp01@acme.com", "Passw0rd", role: "user");

        using (var scope = _factory.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
            db.MemberFinancials.Add(new MemberFinancials
            {
                Id = Guid.NewGuid(),
                MembershipId = target.Id,
                MonthlySalary = 3000,
                ClientHourlyRate = 40,
                VacationReservePercent = 3.33m,
                VacationDaysPerYear = 20,
                Currency = "USD",
                UpdatedAt = DateTime.UtcNow,
            });
            db.VacationReserveTransactions.Add(new VacationReserveTransaction
            {
                Id = Guid.NewGuid(),
                MembershipId = target.Id,
                Type = VacationTransactionTypes.Credit,
                Amount = 500m,
                BillingPeriodMonth = 11,
                BillingPeriodYear = DateTime.UtcNow.Year - 1,
                Description = "stale prior-year credit",
                IsAutoGenerated = true,
                CreatedAt = new DateTime(DateTime.UtcNow.Year - 1, 11, 1, 0, 0, 0, DateTimeKind.Utc),
            });
            await db.SaveChangesAsync();
        }

        var client = await LoggedInClientAsync("admin-exp01@acme.com", "Passw0rd");
        var response = await client.GetAsync($"/api/organizations/{org.Id}/members/{target.Id}/vacation");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = (await response.Content.ReadFromJsonAsync<JsonDocument>())!.RootElement;
        // current-year balance unaffected by prior-year activity
        Assert.Equal(0m, body.GetProperty("balance").GetProperty("reserveBalance").GetDecimal());

        using var scope2 = _factory.Services.CreateScope();
        var verifyDb = scope2.ServiceProvider.GetRequiredService<AppDbContext>();
        var expiry = await verifyDb.VacationReserveTransactions
            .SingleAsync(t => t.MembershipId == target.Id && t.Type == VacationTransactionTypes.Expiry);
        Assert.Equal(-500m, expiry.Amount);
        Assert.False(expiry.IsAutoGenerated);
        Assert.Equal(DateTime.UtcNow.Year - 1, expiry.CreatedAt.Year);

        // idempotent: viewing again does not create a second expiry transaction
        await client.GetAsync($"/api/organizations/{org.Id}/members/{target.Id}/vacation");
        var expiryCount = await verifyDb.VacationReserveTransactions
            .CountAsync(t => t.MembershipId == target.Id && t.Type == VacationTransactionTypes.Expiry);
        Assert.Equal(1, expiryCount);
    }
}
