import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import {
  FINANCIALS_MESSAGES,
  MEMBER_MESSAGES,
  calculateAvailableDays,
  calculateReservePercent,
  can,
  validateMemberFinancials,
  type MemberFinancialsInput,
  type Role,
} from '@devscribed/validation';
import type {
  MemberFinancials,
  VacationRequest,
  VacationReserveTransaction,
} from '@prisma/client';
import type { SessionPayload } from '../auth/session.service';
import { PrismaService } from '../prisma.service';

/** Default `VacationDaysPerYear` (spec 07 requirement 4) — the Prisma column default. */
const DEFAULT_VACATION_DAYS_PER_YEAR = 20;

/** PUT `.../vacation/financials` request body — every field is optional at the wire level. */
export type MemberFinancialsDto = Partial<MemberFinancialsInput>;

/** Full financial block returned to admin/manager (numbers, never Prisma `Decimal`). */
interface FinancialsBlock {
  monthlySalary: number;
  clientHourlyRate: number;
  vacationReservePercent: number;
  isReservePercentManual: boolean;
  vacationDaysPerYear: number;
  currency: string;
}

/** Balance block. Accrual figures are real as of spec 08; requests (used/pending) — spec 09. */
interface BalanceBlock {
  reserveBalance: number | null;
  availableDays: number;
  usedDays: number;
  pendingDays: number;
  totalDaysPerYear: number;
}

/** A single reserve-ledger row on the wire (spec 08 API contract). */
interface TransactionView {
  id: string;
  type: string;
  amount: number;
  billingPeriodMonth: number | null;
  billingPeriodYear: number | null;
  description: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  createdBy: string | null;
}

/** A single vacation request on the wire (spec 09 API contract). */
interface RequestView {
  id: string;
  startDate: string;
  endDate: string;
  workingDays: number;
  deductionAmount: number;
  status: string;
  requestedAt: string;
  reviewedAt: string | null;
  reviewedBy: string | null;
  reviewerComment: string | null;
  cancelledAt: string | null;
  cancelledBy: string | null;
}

export interface VacationView {
  financials: FinancialsBlock | null;
  balance: BalanceBlock | null;
  requests: RequestView[];
  transactions: TransactionView[] | null;
  canEdit: boolean;
  canReviewRequests: boolean;
  canSubmitRequest: boolean;
}

interface CallerMembership {
  id: string;
  role: Role;
  organizationId: string;
  accountId: string;
}

/**
 * Spec 07 — Member Financial Settings. Reads and writes the Vacation tab's financial
 * data. Mirrors `MembersService`: caller resolved from the session (never the URL), the
 * org-row `SELECT ... FOR UPDATE` lock on writes, and the `{ error, message }` /
 * `{ errors }` exception shapes.
 */
@Injectable()
export class VacationService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * `GET /members/:memberId/vacation`. admin/manager see full financials; a `user` sees
   * only their own balance (days, no money); `viewer` — and a `user` viewing another
   * member — get 403 (TC-07-INT-07/08).
   */
  async getVacation(session: SessionPayload, targetId: string): Promise<VacationView> {
    const caller = await this.requireCaller(session);

    const target = await this.prisma.membership.findFirst({
      where: { id: targetId, organizationId: caller.organizationId },
    });
    if (!target) {
      throw new NotFoundException({ error: 'not_found', message: MEMBER_MESSAGES.memberNotFound });
    }

    const canViewAny = can(caller.role, 'view-vacation');
    const isSelf = target.id === caller.id;
    // viewer: no own-balance capability either → forbidden. user: own-balance only.
    if (!canViewAny && !(isSelf && can(caller.role, 'view-own-vacation-balance'))) {
      throw new ForbiddenException({
        error: 'forbidden',
        message: FINANCIALS_MESSAGES.viewForbidden,
      });
    }

    const financials = await this.prisma.memberFinancials.findUnique({
      where: { membershipId: target.id },
    });

    const targetActive = target.status === 'active';
    // Spec 09 flags: review is for a different active member; submit is self-only and
    // requires financials to be configured (submission is impossible without them, so the
    // "Request vacation" affordance stays hidden on an unconfigured member).
    const canReviewRequests =
      can(caller.role, 'review-vacation-requests') && !isSelf && targetActive;
    const canSubmitRequest =
      isSelf && can(caller.role, 'submit-vacation-request') && targetActive && financials !== null;

    if (canViewAny) {
      // admin/manager — full financial view.
      const canEdit = can(caller.role, 'edit-member-financials') && targetActive;
      if (!financials) {
        // No financials ⇒ no requests possible, but keep `requests` an array for the
        // authorized viewer.
        return {
          financials: null,
          balance: null,
          requests: [],
          transactions: null,
          canEdit,
          canReviewRequests,
          canSubmitRequest,
        };
      }

      const transactions = await this.prisma.vacationReserveTransaction.findMany({
        where: { membershipId: target.id },
        orderBy: { createdAt: 'desc' },
      });
      const reserveBalance = this.currentYearBalance(transactions);
      const { requests, usedDays, pendingDays, pendingHold } = await this.loadRequests(target.id);

      return {
        financials: this.toFinancialsBlock(financials),
        balance: this.buildBalance(financials, reserveBalance, false, usedDays, pendingDays, pendingHold),
        requests,
        transactions: transactions.map((t) => this.toTransactionView(t)),
        canEdit,
        canReviewRequests,
        canSubmitRequest,
      };
    }

    // user viewing own membership — days only, never money nor the ledger.
    if (!financials) {
      return {
        financials: null,
        balance: null,
        requests: [],
        transactions: null,
        canEdit: false,
        canReviewRequests,
        canSubmitRequest,
      };
    }

    // availableDays is computed server-side from the real reserve balance even though the
    // monetary balance itself is hidden (null) from the user.
    const transactions = await this.prisma.vacationReserveTransaction.findMany({
      where: { membershipId: target.id },
      select: { amount: true, createdAt: true },
    });
    const reserveBalance = this.currentYearBalance(transactions);
    const { requests, usedDays, pendingDays, pendingHold } = await this.loadRequests(target.id);

    return {
      financials: null,
      balance: this.buildBalance(financials, reserveBalance, true, usedDays, pendingDays, pendingHold),
      requests,
      transactions: null,
      canEdit: false,
      canReviewRequests,
      canSubmitRequest,
    };
  }

  /**
   * Current-calendar-year requests for a membership (spec 09): all statuses, newest first
   * (by `requestedAt`), plus the aggregates the balance block needs — `usedDays` (approved
   * working days), `pendingDays` (pending working days), and `pendingHold` (pending
   * deduction amounts). The current-year filter is by `startDate`.
   */
  private async loadRequests(membershipId: string): Promise<{
    requests: RequestView[];
    usedDays: number;
    pendingDays: number;
    pendingHold: number;
  }> {
    const currentYear = new Date().getUTCFullYear();
    const all = await this.prisma.vacationRequest.findMany({
      where: { membershipId },
      orderBy: { requestedAt: 'desc' },
    });
    const currentYearRequests = all.filter(
      (r) => r.startDate.getUTCFullYear() === currentYear,
    );

    let usedDays = 0;
    let pendingDays = 0;
    let pendingHold = 0;
    for (const r of currentYearRequests) {
      if (r.status === 'approved') usedDays += r.workingDays;
      else if (r.status === 'pending') {
        pendingDays += r.workingDays;
        pendingHold += r.deductionAmount.toNumber();
      }
    }

    return {
      requests: currentYearRequests.map((r) => this.toRequestView(r)),
      usedDays,
      pendingDays,
      pendingHold,
    };
  }

  /** Prisma request row → wire shape (Decimal → number, dates → 'YYYY-MM-DD'/ISO). */
  private toRequestView(r: VacationRequest): RequestView {
    return {
      id: r.id,
      startDate: r.startDate.toISOString().slice(0, 10),
      endDate: r.endDate.toISOString().slice(0, 10),
      workingDays: r.workingDays,
      deductionAmount: r.deductionAmount.toNumber(),
      status: r.status,
      requestedAt: r.requestedAt.toISOString(),
      reviewedAt: r.reviewedAt ? r.reviewedAt.toISOString() : null,
      reviewedBy: r.reviewedByAccountId ?? null,
      reviewerComment: r.reviewerComment ?? null,
      cancelledAt: r.cancelledAt ? r.cancelledAt.toISOString() : null,
      cancelledBy: r.cancelledByAccountId ?? null,
    };
  }

  /**
   * `PUT /members/:memberId/vacation/financials`. Upserts the settings and appends an
   * immutable snapshot with `EffectiveFrom` = today. In auto mode the reserve percent is
   * recomputed from salary/rate/days; in manual mode the validated value is stored.
   */
  async updateFinancials(
    session: SessionPayload,
    targetId: string,
    dto: MemberFinancialsDto,
  ): Promise<{ success: true; vacationReservePercent: number }> {
    const caller = await this.requireCaller(session);
    if (!can(caller.role, 'edit-member-financials')) {
      throw new ForbiddenException({
        error: 'forbidden',
        message: FINANCIALS_MESSAGES.editForbidden,
      });
    }

    return this.prisma.$transaction(async (tx) => {
      // Same org-row lock the members flows take — serializes concurrent writes against
      // this membership's single financials/snapshot chain.
      await tx.$queryRaw`SELECT id FROM "Organization" WHERE id = ${caller.organizationId} FOR UPDATE`;

      const target = await tx.membership.findFirst({
        where: { id: targetId, organizationId: caller.organizationId },
      });
      if (!target) {
        throw new NotFoundException({ error: 'not_found', message: MEMBER_MESSAGES.memberNotFound });
      }
      if (target.status === 'removed') {
        throw new BadRequestException({
          error: 'member_removed',
          message: FINANCIALS_MESSAGES.memberRemoved,
        });
      }

      const validation = validateMemberFinancials(dto);
      if (!validation.valid) {
        throw new BadRequestException({ errors: validation.errors });
      }

      const { monthlySalary, clientHourlyRate, vacationDaysPerYear, currency, isReservePercentManual } =
        validation.value;

      // Auto mode recomputes from the freshly validated inputs (requirements 7-8); manual
      // mode stores the value the manager supplied (requirement 9) — already validated non-null.
      const vacationReservePercent = isReservePercentManual
        ? (validation.value.vacationReservePercent as number)
        : calculateReservePercent({ monthlySalary, clientHourlyRate, vacationDaysPerYear });

      const values = {
        monthlySalary,
        clientHourlyRate,
        vacationReservePercent,
        isReservePercentManual,
        vacationDaysPerYear,
        currency,
      };

      await tx.memberFinancials.upsert({
        where: { membershipId: target.id },
        create: { membershipId: target.id, ...values, updatedByAccountId: caller.accountId },
        update: { ...values, updatedByAccountId: caller.accountId },
      });

      // Every write appends an immutable snapshot (requirement 11); prior snapshots are
      // never touched. `effectiveFrom` is today, date-only (midnight UTC).
      await tx.memberFinancialsSnapshot.create({
        data: { membershipId: target.id, ...values, effectiveFrom: this.today() },
      });

      return { success: true as const, vacationReservePercent };
    });
  }

  /** Prisma `Decimal` → `number` for the wire. */
  private toFinancialsBlock(f: MemberFinancials): FinancialsBlock {
    return {
      monthlySalary: f.monthlySalary.toNumber(),
      clientHourlyRate: f.clientHourlyRate.toNumber(),
      vacationReservePercent: f.vacationReservePercent.toNumber(),
      isReservePercentManual: f.isReservePercentManual,
      vacationDaysPerYear: f.vacationDaysPerYear,
      currency: f.currency,
    };
  }

  /**
   * Reserve balance = SUM of transaction amounts whose `createdAt` falls in the current
   * calendar year (spec requirement 15; unused balances expire at year-end, expressed as
   * a current-year filter). Prisma `Decimal` summed as `number`.
   */
  private currentYearBalance(
    transactions: readonly Pick<VacationReserveTransaction, 'amount' | 'createdAt'>[],
  ): number {
    const currentYear = new Date().getUTCFullYear();
    return transactions.reduce(
      (sum, t) =>
        t.createdAt.getUTCFullYear() === currentYear ? sum + t.amount.toNumber() : sum,
      0,
    );
  }

  /**
   * Balance block from the real reserve balance and the current-year request aggregates
   * (spec 09). `availableDays` folds in the pending hold (requirement 8). `hideReserve`
   * nulls the monetary figure for a `user` viewing their own membership while still
   * exposing the computed available days.
   */
  private buildBalance(
    financials: MemberFinancials,
    reserveBalance: number,
    hideReserve: boolean,
    usedDays: number,
    pendingDays: number,
    pendingHold: number,
  ): BalanceBlock {
    const availableDays = calculateAvailableDays({
      reserveBalance,
      monthlySalary: financials.monthlySalary.toNumber(),
      vacationDaysPerYear: financials.vacationDaysPerYear,
      usedDays,
      pendingHold,
    });
    return {
      reserveBalance: hideReserve ? null : reserveBalance,
      availableDays,
      usedDays,
      pendingDays,
      totalDaysPerYear: financials.vacationDaysPerYear ?? DEFAULT_VACATION_DAYS_PER_YEAR,
    };
  }

  /** Prisma ledger row → wire shape (`Decimal` → number, dates → ISO, createdBy id or null). */
  private toTransactionView(t: VacationReserveTransaction): TransactionView {
    return {
      id: t.id,
      type: t.type,
      amount: t.amount.toNumber(),
      billingPeriodMonth: t.billingPeriodMonth,
      billingPeriodYear: t.billingPeriodYear,
      description: t.description,
      isAutoGenerated: t.isAutoGenerated,
      createdAt: t.createdAt.toISOString(),
      createdBy: t.createdByAccountId ?? null,
    };
  }

  /** Today as a date-only value (midnight UTC), for the snapshot's `@db.Date` column. */
  private today(): Date {
    const now = new Date();
    return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  }

  /** Caller's own membership, resolved from the session — mirrors `MembersService`. */
  private async requireCaller(session: SessionPayload): Promise<CallerMembership> {
    const caller = await this.prisma.membership.findUnique({
      where: { accountId: session.accountId },
    });
    if (!caller || caller.status !== 'active' || caller.organizationId !== session.organizationId) {
      throw new ForbiddenException();
    }
    return {
      id: caller.id,
      role: caller.role as Role,
      organizationId: caller.organizationId,
      accountId: caller.accountId,
    };
  }
}
