using Devscribed.Admin.Web.Models;
using Devscribed.Admin.Web.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Playwright.NUnit;

namespace Devscribed.Admin.Tests.E2E;

[TestFixture]
public class OrganizationRequestsE2ETests : PageTest
{
    private E2EServerFixture _server = null!;

    [SetUp]
    public void SetUp()
    {
        _server = new E2EServerFixture();
    }

    [TearDown]
    public void TearDown()
    {
        _server.Dispose();
    }

    private Account SeedAdditionalMember(Guid organizationId, string email, string password, string role, string firstName, string lastName)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        var hasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher>();

        var account = new Account
        {
            Id = Guid.NewGuid(),
            Email = email,
            PasswordHash = hasher.Hash(password),
            FirstName = firstName,
            LastName = lastName,
            CreatedAt = DateTime.UtcNow,
        };
        db.Accounts.Add(account);
        db.Memberships.Add(new Membership
        {
            Id = Guid.NewGuid(),
            AccountId = account.Id,
            OrganizationId = organizationId,
            Role = role,
            Status = "active",
            JoinedAt = DateTime.UtcNow,
        });
        db.SaveChanges();
        return account;
    }

    private Guid GetOrgId(string email)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        return db.Memberships.Include(m => m.Account).Single(m => m.Account.Email == email).OrganizationId;
    }

    private Guid GetMembershipId(string email)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        return db.Memberships.Include(m => m.Account).Single(m => m.Account.Email == email).Id;
    }

    private void ConfigureFinancialsAndCredit(Guid membershipId, decimal monthlySalary, decimal creditAmount, int vacationDaysPerYear = 20)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        var ledger = scope.ServiceProvider.GetRequiredService<VacationLedgerService>();

        db.MemberFinancials.Add(new MemberFinancials
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            MonthlySalary = monthlySalary,
            ClientHourlyRate = 40,
            VacationReservePercent = 3.33m,
            VacationDaysPerYear = vacationDaysPerYear,
            Currency = "USD",
            UpdatedAt = DateTime.UtcNow,
        });
        ledger.PostTransaction(membershipId, VacationTransactionTypes.Credit, creditAmount, "seed credit", isAutoGenerated: true);
        db.SaveChanges();
    }

    private VacationRequest SeedRequest(Guid membershipId, DateOnly start, DateOnly end, int workingDays, decimal deductionAmount, string status)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        var request = new VacationRequest
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            StartDate = start,
            EndDate = end,
            WorkingDays = workingDays,
            DeductionAmount = deductionAmount,
            Status = status,
            RequestedAt = DateTime.UtcNow,
        };
        db.VacationRequests.Add(request);
        db.SaveChanges();
        return request;
    }

    private void SeedDebit(Guid membershipId, Guid requestId, decimal amount)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        var ledger = scope.ServiceProvider.GetRequiredService<VacationLedgerService>();
        ledger.PostTransaction(membershipId, VacationTransactionTypes.Debit, -amount, "seed debit", isAutoGenerated: false, vacationRequestId: requestId);
        db.SaveChanges();
    }

    private static DateOnly FutureMonday(int weeksAhead)
    {
        var today = DateTime.UtcNow.Date;
        var daysUntilMonday = ((int)DayOfWeek.Monday - (int)today.DayOfWeek + 7) % 7;
        if (daysUntilMonday == 0) daysUntilMonday = 7;
        return DateOnly.FromDateTime(today.AddDays(daysUntilMonday + weeksAhead * 7));
    }

    private async Task LoginAsync(string email, string password)
    {
        await Page.GotoAsync($"{_server.BaseUrl}/login");
        await Page.GetByTestId("login-email-input").FillAsync(email);
        await Page.GetByTestId("login-password-input").FillAsync(password);
        await Page.GetByTestId("login-submit-button").ClickAsync();
        await Page.WaitForURLAsync("**/members");
    }

    // TC-10-E2E-01: Manager reviews requests from Requests page
    [Test]
    public async Task Manager_reviews_requests_from_requests_page()
    {
        _server.SeedAccount("admin-e2e-orgreq1@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-orgreq1@acme.com");
        SeedAdditionalMember(orgId, "manager-e2e-orgreq1@acme.com", "Passw0rd", "manager", "Man", "Ager");
        SeedAdditionalMember(orgId, "alex-e2e-orgreq1@acme.com", "Passw0rd", "user", "Alex", "Kaminski");
        SeedAdditionalMember(orgId, "jane-e2e-orgreq1@acme.com", "Passw0rd", "user", "Jane", "Smith");
        var alexId = GetMembershipId("alex-e2e-orgreq1@acme.com");
        var janeId = GetMembershipId("jane-e2e-orgreq1@acme.com");
        ConfigureFinancialsAndCredit(alexId, 3000, 5000m);
        ConfigureFinancialsAndCredit(janeId, 3000, 5000m);

        var start1 = FutureMonday(1);
        var r1 = SeedRequest(alexId, start1, start1.AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);
        var start2 = FutureMonday(2);
        var r2 = SeedRequest(janeId, start2, start2.AddDays(2), 3, 415.38m, VacationRequestStatuses.Pending);

        await LoginAsync("manager-e2e-orgreq1@acme.com", "Passw0rd");
        await Page.GetByTestId("sidebar-requests-link").ClickAsync();
        await Expect(Page.GetByTestId("requests-page")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId("sidebar-requests-badge")).ToHaveTextAsync("2");

        await Expect(Page.GetByTestId($"requests-card-{r1.Id}")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"requests-card-{r2.Id}")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"requests-card-avatar-{r1.Id}")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"requests-card-member-name-{r1.Id}")).ToContainTextAsync("Alex Kaminski");

        await Page.GetByTestId($"requests-card-approve-{r1.Id}").ClickAsync();
        await Expect(Page.GetByTestId("toast-request-approved")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"requests-card-status-{r1.Id}")).ToContainTextAsync("Approved");

        await Page.GetByTestId($"requests-card-reject-{r2.Id}").ClickAsync();
        await Expect(Page.GetByTestId("vacation-reject-modal")).ToBeVisibleAsync();
        await Page.GetByTestId("vacation-reject-comment-input").FillAsync("Team availability conflict");
        await Page.GetByTestId("vacation-reject-confirm-btn").ClickAsync();

        await Expect(Page.GetByTestId("toast-request-rejected")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"requests-card-status-{r2.Id}")).ToContainTextAsync("Rejected");
        await Expect(Page.GetByTestId($"requests-card-reviewer-comment-{r2.Id}")).ToContainTextAsync("Team availability conflict");

        await Expect(Page.GetByTestId("sidebar-requests-badge")).Not.ToBeVisibleAsync();
    }

    // TC-10-E2E-02: Requests page — status filter
    [Test]
    public async Task Status_filter_updates_displayed_requests()
    {
        _server.SeedAccount("admin-e2e-orgreq2@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-orgreq2@acme.com");
        SeedAdditionalMember(orgId, "alex-e2e-orgreq2@acme.com", "Passw0rd", "user", "Alex", "One");
        var memberId = GetMembershipId("alex-e2e-orgreq2@acme.com");
        ConfigureFinancialsAndCredit(memberId, 3000, 5000m);

        SeedRequest(memberId, FutureMonday(1), FutureMonday(1).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);
        SeedRequest(memberId, FutureMonday(2), FutureMonday(2).AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);
        SeedRequest(memberId, FutureMonday(3), FutureMonday(3).AddDays(4), 5, 692.31m, VacationRequestStatuses.Approved);
        var rejected = SeedRequest(memberId, FutureMonday(4), FutureMonday(4).AddDays(4), 5, 692.31m, VacationRequestStatuses.Rejected);

        await LoginAsync("admin-e2e-orgreq2@acme.com", "Passw0rd");
        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/requests");

        var pendingCards = Page.Locator("div.requests-card");
        await Expect(pendingCards).ToHaveCountAsync(2);

        await Page.GetByTestId("requests-status-filter").SelectOptionAsync("all");
        await Expect(pendingCards).ToHaveCountAsync(4);

        await Page.GetByTestId("requests-status-filter").SelectOptionAsync("approved");
        await Expect(pendingCards).ToHaveCountAsync(1);

        await Page.GetByTestId("requests-status-filter").SelectOptionAsync("rejected");
        await Expect(pendingCards).ToHaveCountAsync(1);
        await Expect(Page.GetByTestId($"requests-card-status-{rejected.Id}")).ToContainTextAsync("Rejected");
    }

    // TC-10-E2E-03: Requests page — user and viewer cannot access
    [Test]
    public async Task User_and_viewer_cannot_access_requests_page()
    {
        _server.SeedAccount("admin-e2e-orgreq3@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-orgreq3@acme.com");
        SeedAdditionalMember(orgId, "user-e2e-orgreq3@acme.com", "Passw0rd", "user", "User", "Three");

        await LoginAsync("user-e2e-orgreq3@acme.com", "Passw0rd");
        await Expect(Page.GetByTestId("sidebar-requests-link")).Not.ToBeVisibleAsync();

        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/requests");
        await Page.WaitForURLAsync("**/members");
    }

    // TC-10-E2E-04: Requests page — cancel approved request
    [Test]
    public async Task Manager_cancels_approved_request_from_requests_page()
    {
        _server.SeedAccount("admin-e2e-orgreq4@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-orgreq4@acme.com");
        SeedAdditionalMember(orgId, "manager-e2e-orgreq4@acme.com", "Passw0rd", "manager", "Man", "Ager");
        SeedAdditionalMember(orgId, "alex-e2e-orgreq4@acme.com", "Passw0rd", "user", "Alex", "Four");
        var memberId = GetMembershipId("alex-e2e-orgreq4@acme.com");
        ConfigureFinancialsAndCredit(memberId, 3000, 5000m);

        var start = FutureMonday(1);
        var request = SeedRequest(memberId, start, start.AddDays(4), 5, 692.31m, VacationRequestStatuses.Approved);
        SeedDebit(memberId, request.Id, 692.31m);

        await LoginAsync("manager-e2e-orgreq4@acme.com", "Passw0rd");
        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/requests");
        await Page.GetByTestId("requests-status-filter").SelectOptionAsync("all");

        Page.Dialog += async (_, dialog) => await dialog.AcceptAsync();
        await Page.GetByTestId($"requests-card-cancel-{request.Id}").ClickAsync();

        await Expect(Page.GetByTestId("toast-request-cancelled")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId("toast-request-cancelled")).ToContainTextAsync("reserve refunded");
        await Expect(Page.GetByTestId($"requests-card-status-{request.Id}")).ToContainTextAsync("Cancelled");
    }
}
