using Devscribed.Admin.Web.Models;
using Devscribed.Admin.Web.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Playwright.NUnit;

namespace Devscribed.Admin.Tests.E2E;

[TestFixture]
public class VacationRequestsE2ETests : PageTest
{
    private E2EServerFixture _server = null!;

    [SetUp]
    public void SetUp()
    {
        _server = new E2EServerFixture();
    }

    [TearDown]
    public void TearDown()
    {
        _server.Dispose();
    }

    private Account SeedAdditionalMember(Guid organizationId, string email, string password, string role, string firstName, string lastName)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        var hasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher>();

        var account = new Account
        {
            Id = Guid.NewGuid(),
            Email = email,
            PasswordHash = hasher.Hash(password),
            FirstName = firstName,
            LastName = lastName,
            CreatedAt = DateTime.UtcNow,
        };
        db.Accounts.Add(account);
        db.Memberships.Add(new Membership
        {
            Id = Guid.NewGuid(),
            AccountId = account.Id,
            OrganizationId = organizationId,
            Role = role,
            Status = "active",
            JoinedAt = DateTime.UtcNow,
        });
        db.SaveChanges();
        return account;
    }

    private Guid GetOrgId(string email)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        return db.Memberships.Include(m => m.Account).Single(m => m.Account.Email == email).OrganizationId;
    }

    private Guid GetMembershipId(string email)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        return db.Memberships.Include(m => m.Account).Single(m => m.Account.Email == email).Id;
    }

    private void ConfigureFinancialsAndCredit(Guid membershipId, decimal monthlySalary, decimal creditAmount, int vacationDaysPerYear = 20)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        var ledger = scope.ServiceProvider.GetRequiredService<VacationLedgerService>();

        db.MemberFinancials.Add(new MemberFinancials
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            MonthlySalary = monthlySalary,
            ClientHourlyRate = 40,
            VacationReservePercent = 3.33m,
            VacationDaysPerYear = vacationDaysPerYear,
            Currency = "USD",
            UpdatedAt = DateTime.UtcNow,
        });
        ledger.PostTransaction(membershipId, VacationTransactionTypes.Credit, creditAmount, "seed credit", isAutoGenerated: true);
        db.SaveChanges();
    }

    private VacationRequest SeedRequest(Guid membershipId, DateOnly start, DateOnly end, int workingDays, decimal deductionAmount, string status)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        var request = new VacationRequest
        {
            Id = Guid.NewGuid(),
            MembershipId = membershipId,
            StartDate = start,
            EndDate = end,
            WorkingDays = workingDays,
            DeductionAmount = deductionAmount,
            Status = status,
            RequestedAt = DateTime.UtcNow,
        };
        db.VacationRequests.Add(request);
        db.SaveChanges();
        return request;
    }

    private void SeedDebit(Guid membershipId, Guid requestId, decimal amount)
    {
        using var scope = _server.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Devscribed.Admin.Web.Data.AppDbContext>();
        var ledger = scope.ServiceProvider.GetRequiredService<VacationLedgerService>();
        ledger.PostTransaction(membershipId, VacationTransactionTypes.Debit, -amount, "seed debit", isAutoGenerated: false, vacationRequestId: requestId);
        db.SaveChanges();
    }

    private static DateOnly FutureMonday(int weeksAhead)
    {
        var today = DateTime.UtcNow.Date;
        var daysUntilMonday = ((int)DayOfWeek.Monday - (int)today.DayOfWeek + 7) % 7;
        if (daysUntilMonday == 0) daysUntilMonday = 7;
        return DateOnly.FromDateTime(today.AddDays(daysUntilMonday + weeksAhead * 7));
    }

    private async Task LoginAsync(string email, string password)
    {
        await Page.GotoAsync($"{_server.BaseUrl}/login");
        await Page.GetByTestId("login-email-input").FillAsync(email);
        await Page.GetByTestId("login-password-input").FillAsync(password);
        await Page.GetByTestId("login-submit-button").ClickAsync();
        await Page.WaitForURLAsync("**/members");
    }

    // TC-09-E2E-01: User submits vacation request
    [Test]
    public async Task User_submits_vacation_request()
    {
        _server.SeedAccount("admin-e2e-req1@acme.com", "Passw0rd", "Pat", "Owner", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-req1@acme.com");
        SeedAdditionalMember(orgId, "alex-e2e-req1@acme.com", "Passw0rd", "user", "Alex", "Kaminski");
        var memberId = GetMembershipId("alex-e2e-req1@acme.com");
        ConfigureFinancialsAndCredit(memberId, 3000, 1384.62m); // ~10 available days

        var start = FutureMonday(1);
        var end = start.AddDays(4);

        await LoginAsync("alex-e2e-req1@acme.com", "Passw0rd");
        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/members/{memberId}");
        await Page.GetByTestId("member-detail-tab-vacation").ClickAsync();

        await Expect(Page.GetByTestId("vacation-balance-card")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId("vacation-available-days")).ToHaveTextAsync("10");
        await Expect(Page.GetByTestId("vacation-financials-card")).Not.ToBeVisibleAsync();

        await Page.GetByTestId("vacation-request-btn").ClickAsync();
        await Expect(Page.GetByTestId("vacation-request-modal")).ToBeVisibleAsync();

        await Page.GetByTestId("vacation-start-date-input").FillAsync(start.ToString("yyyy-MM-dd"));
        await Page.GetByTestId("vacation-end-date-input").FillAsync(end.ToString("yyyy-MM-dd"));

        await Expect(Page.GetByTestId("vacation-working-days-preview")).ToHaveTextAsync("5");

        await Page.GetByTestId("vacation-request-submit-btn").ClickAsync();

        await Expect(Page.GetByTestId("toast-request-submitted")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId("vacation-available-days")).ToHaveTextAsync("5");
    }

    // TC-09-E2E-02: Manager approves request from Vacation tab
    [Test]
    public async Task Manager_approves_request_from_vacation_tab()
    {
        _server.SeedAccount("admin-e2e-req2@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-req2@acme.com");
        SeedAdditionalMember(orgId, "manager-e2e-req2@acme.com", "Passw0rd", "manager", "Man", "Ager");
        SeedAdditionalMember(orgId, "alex-e2e-req2@acme.com", "Passw0rd", "user", "Alex", "Two");
        var memberId = GetMembershipId("alex-e2e-req2@acme.com");
        ConfigureFinancialsAndCredit(memberId, 3000, 5000m);

        var start = FutureMonday(1);
        var request = SeedRequest(memberId, start, start.AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        await LoginAsync("manager-e2e-req2@acme.com", "Passw0rd");
        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/members/{memberId}");
        await Page.GetByTestId("member-detail-tab-vacation").ClickAsync();

        await Page.GetByTestId($"vacation-request-approve-{request.Id}").ClickAsync();

        await Expect(Page.GetByTestId("toast-request-approved")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"vacation-request-status-{request.Id}")).ToContainTextAsync("Approved");
        await Expect(Page.GetByTestId("vacation-used-days")).ToHaveTextAsync("5");
        await Expect(Page.GetByTestId("vacation-pending-days")).ToHaveTextAsync("0");
    }

    // TC-09-E2E-03: User cancels own pending request
    [Test]
    public async Task User_cancels_own_pending_request()
    {
        _server.SeedAccount("admin-e2e-req3@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-req3@acme.com");
        SeedAdditionalMember(orgId, "alex-e2e-req3@acme.com", "Passw0rd", "user", "Alex", "Three");
        var memberId = GetMembershipId("alex-e2e-req3@acme.com");
        ConfigureFinancialsAndCredit(memberId, 3000, 5000m);

        var start = FutureMonday(1);
        var request = SeedRequest(memberId, start, start.AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        await LoginAsync("alex-e2e-req3@acme.com", "Passw0rd");
        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/members/{memberId}");
        await Page.GetByTestId("member-detail-tab-vacation").ClickAsync();

        Page.Dialog += async (_, dialog) => await dialog.AcceptAsync();
        await Page.GetByTestId($"vacation-request-cancel-{request.Id}").ClickAsync();

        await Expect(Page.GetByTestId("toast-request-cancelled")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"vacation-request-status-{request.Id}")).ToContainTextAsync("Cancelled");
    }

    // TC-09-E2E-04: Manager cancels approved request (refund)
    [Test]
    public async Task Manager_cancels_approved_request_with_refund()
    {
        _server.SeedAccount("admin-e2e-req4@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-req4@acme.com");
        SeedAdditionalMember(orgId, "manager-e2e-req4@acme.com", "Passw0rd", "manager", "Man", "Ager");
        SeedAdditionalMember(orgId, "alex-e2e-req4@acme.com", "Passw0rd", "user", "Alex", "Four");
        var memberId = GetMembershipId("alex-e2e-req4@acme.com");
        ConfigureFinancialsAndCredit(memberId, 3000, 5000m);

        var start = FutureMonday(1);
        var request = SeedRequest(memberId, start, start.AddDays(4), 5, 692.31m, VacationRequestStatuses.Approved);
        SeedDebit(memberId, request.Id, 692.31m);

        await LoginAsync("manager-e2e-req4@acme.com", "Passw0rd");
        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/members/{memberId}");
        await Page.GetByTestId("member-detail-tab-vacation").ClickAsync();

        Page.Dialog += async (_, dialog) => await dialog.AcceptAsync();
        await Page.GetByTestId($"vacation-request-cancel-{request.Id}").ClickAsync();

        await Expect(Page.GetByTestId("toast-request-cancelled")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId("toast-request-cancelled")).ToContainTextAsync("reserve refunded");
        await Expect(Page.GetByTestId($"vacation-request-status-{request.Id}")).ToContainTextAsync("Cancelled");
        await Expect(Page.GetByTestId("vacation-reserve-amount")).ToContainTextAsync("5000.00");
        await Expect(Page.GetByTestId("vacation-transactions-table")).ToContainTextAsync("Refund");
    }

    // TC-09-E2E-05: Insufficient balance blocks request submission
    [Test]
    public async Task Insufficient_balance_blocks_request_submission()
    {
        _server.SeedAccount("admin-e2e-req5@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-req5@acme.com");
        SeedAdditionalMember(orgId, "alex-e2e-req5@acme.com", "Passw0rd", "user", "Alex", "Five");
        var memberId = GetMembershipId("alex-e2e-req5@acme.com");
        ConfigureFinancialsAndCredit(memberId, 3000, 276.93m); // ~2 available days

        var start = FutureMonday(1);

        await LoginAsync("alex-e2e-req5@acme.com", "Passw0rd");
        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/members/{memberId}");
        await Page.GetByTestId("member-detail-tab-vacation").ClickAsync();

        await Page.GetByTestId("vacation-request-btn").ClickAsync();
        await Page.GetByTestId("vacation-start-date-input").FillAsync(start.ToString("yyyy-MM-dd"));
        await Page.GetByTestId("vacation-end-date-input").FillAsync(start.AddDays(4).ToString("yyyy-MM-dd"));
        await Page.GetByTestId("vacation-request-submit-btn").ClickAsync();

        await Expect(Page.GetByTestId("vacation-request-error")).ToContainTextAsync("Insufficient vacation balance. You have 2 day(s) available.");
        await Expect(Page.GetByTestId("vacation-request-modal")).ToBeVisibleAsync();
    }

    // TC-09-E2E-06: Self-approval blocked in UI
    [Test]
    public async Task Self_approval_is_blocked_in_ui()
    {
        var admin = _server.SeedAccount("admin-e2e-req6@acme.com", "Passw0rd", orgName: "Acme Inc", role: "admin");
        var orgId = GetOrgId("admin-e2e-req6@acme.com");
        var memberId = GetMembershipId("admin-e2e-req6@acme.com");
        ConfigureFinancialsAndCredit(memberId, 3000, 5000m);

        var start = FutureMonday(1);
        var request = SeedRequest(memberId, start, start.AddDays(4), 5, 692.31m, VacationRequestStatuses.Pending);

        await LoginAsync("admin-e2e-req6@acme.com", "Passw0rd");
        await Page.GotoAsync($"{_server.BaseUrl}/org/{orgId}/members/{memberId}");
        await Page.GetByTestId("member-detail-tab-vacation").ClickAsync();

        await Expect(Page.GetByTestId($"vacation-request-row-{request.Id}")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"vacation-request-approve-{request.Id}")).Not.ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"vacation-request-reject-{request.Id}")).Not.ToBeVisibleAsync();
        await Expect(Page.GetByTestId($"vacation-request-cancel-{request.Id}")).ToBeVisibleAsync();
    }
}
