# Every input, with a type and a description.
#
# The rule this file follows: **an input that should be identical in both environments has
# its value here, not in a tfvars file.** A value that appears in both dev.tfvars and
# prod.tfvars is a value someone can edit in one of them by accident, and the two
# environments then differ in a way nobody chose. The brief asks for the same shape in
# both, scalable by changing numbers — so the numbers live here, once.
#
# What is left in environments/*.tfvars is only what genuinely differs: the environment
# name, its address space, whether its bucket may be destroyed, and who gets its alarms.
#
# NO SECRET IS EVER SET HERE OR IN A TFVARS FILE. The session secret, the internal task
# secret, and the database password are generated by Terraform; the SES identities are
# verified out of band by a human clicking a link.

# ---------------------------------------------------------------------------------------
# Environment identity
# ---------------------------------------------------------------------------------------

variable "env" {
  description = "Environment name. Suffixes every resource name."
  type        = string

  validation {
    condition     = contains(["dev", "prod"], var.env)
    error_message = "env must be dev or prod. There are two environments and no workspaces."
  }
}

variable "aws_region" {
  description = "Region for every resource in this root module."
  type        = string
  default     = "us-west-1"
}

variable "availability_zones" {
  description = <<-EOT
    Exactly two, and us-west-1 has exactly two to give. Both a load balancer and an RDS
    subnet group require two zones even when only one is used.
  EOT
  type        = list(string)
  default     = ["us-west-1a", "us-west-1c"]
}

variable "vpc_cidr" {
  description = "Address space for this environment. Distinct per environment so the two could be peered later."
  type        = string
}

# ---------------------------------------------------------------------------------------
# Images
# ---------------------------------------------------------------------------------------

variable "web_image" {
  description = <<-EOT
    Image the web service runs. `make deploy-*` resolves the digest of what it just pushed
    and passes it here, so what a plan promises is what runs. Left unset — a plain
    `terraform apply` — it falls back to the `latest` tag in this environment's registry.
  EOT
  type        = string
  default     = null
}

variable "api_image" {
  description = "Image the API service, the migration task, and the sweep task run. Same rule."
  type        = string
  default     = null
}

# ---------------------------------------------------------------------------------------
# Sizing — identical in both environments, per the brief. Scale by editing here.
# ---------------------------------------------------------------------------------------

variable "web_cpu" {
  description = "Fargate CPU units for a web task. 256 is a quarter vCPU and the smallest Fargate sells."
  type        = number
  default     = 256
}

variable "web_memory" {
  description = "MiB for a web task. 512 is the floor for 256 CPU units."
  type        = number
  default     = 512
}

variable "api_cpu" {
  description = "Fargate CPU units for an API task."
  type        = number
  default     = 256
}

variable "api_memory" {
  description = <<-EOT
    MiB for an API task. Double the web app's, because this container launches Chromium to
    render signed PDFs and Chromium in 512 MiB dies mid-render. If PDF rendering turns out
    slow, this and `api_cpu` are the two numbers to raise.
  EOT
  type        = number
  default     = 1024
}

variable "web_min_tasks" {
  description = "Autoscaling floor for the web service."
  type        = number
  default     = 1
}

variable "web_max_tasks" {
  description = "Autoscaling ceiling for the web service."
  type        = number
  default     = 4
}

variable "api_min_tasks" {
  description = "Autoscaling floor for the API service."
  type        = number
  default     = 1
}

variable "api_max_tasks" {
  description = "Autoscaling ceiling for the API service."
  type        = number
  default     = 4
}

variable "scaling_target_cpu" {
  description = "Average CPU percentage both services scale to hold."
  type        = number
  default     = 65
}

variable "desired_count_override" {
  description = <<-EOT
    Forces both services to this many tasks. `make stop-<env>` passes 0 and
    `make start-<env>` clears it — how an environment nobody is using overnight stops
    costing compute without being destroyed. The load balancer and the database keep
    running; only Fargate stops.
  EOT
  type        = number
  default     = null
}

variable "web_port" {
  description = "Port the web container listens on."
  type        = number
  default     = 3000
}

variable "api_port" {
  description = "Port the API container listens on."
  type        = number
  default     = 4000
}

# ---------------------------------------------------------------------------------------
# Database — identical shape in both environments
# ---------------------------------------------------------------------------------------

variable "db_instance_class" {
  description = "Graviton burstable. The first thing to change when the database is the bottleneck."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_engine_version" {
  description = "Postgres version. Pinned so a plan describes the version it will run."
  type        = string
  default     = "17.6"
}

variable "db_allocated_storage" {
  description = "GB at rest. gp3's floor is 20."
  type        = number
  default     = 20
}

variable "db_max_allocated_storage" {
  description = "Ceiling for RDS storage autoscaling."
  type        = number
  default     = 100
}

variable "db_multi_az" {
  description = "Standby in a second zone. Doubles the instance cost."
  type        = bool
  default     = false
}

variable "ssl_root_cert_path" {
  description = <<-EOT
    Where the RDS certificate authority bundle sits inside the API image. It is downloaded
    by apps/api/Dockerfile and named in the connection string, so the two must agree.
  EOT
  type        = string
  default     = "/etc/ssl/certs/rds-global-bundle.pem"
}

variable "db_backup_retention_days" {
  description = "Automated backup retention, in days."
  type        = number
  default     = 7
}

# ---------------------------------------------------------------------------------------
# Application behaviour — identical in both environments on purpose
#
# An environment that behaves differently from production is not a test of production.
# ---------------------------------------------------------------------------------------

variable "signing_token_ttl_days" {
  description = "Lifetime of a signing link, in days."
  type        = number
  default     = 14
}

variable "envelope_expiry_days" {
  description = "Default envelope expiry, in days, applied at send."
  type        = number
  default     = 30
}

# ---------------------------------------------------------------------------------------
# Differs between environments
# ---------------------------------------------------------------------------------------

variable "documents_bucket" {
  description = <<-EOT
    Name of the signed-documents bucket. Null derives
    `devscribed-documents-{env}-{account}`, which is what both environments do: the
    account id is not knowable statically and `env` is the only part that differs.
  EOT
  type        = string
  default     = null
}

variable "object_lock_years" {
  description = <<-EOT
    Default Object Lock retention in years, GOVERNANCE mode. 0 disables it — which is what
    dev does, because locked dev objects cannot be cleaned up and make the environment
    unusable within weeks.
  EOT
  type        = number

  validation {
    condition     = var.object_lock_years >= 0 && var.object_lock_years <= 100
    error_message = "object_lock_years must be between 0 and 100."
  }
}

variable "bucket_force_destroy" {
  description = "Whether `terraform destroy` may empty and remove the buckets. Never true in prod."
  type        = bool
}

variable "db_deletion_protection" {
  description = "Whether RDS refuses to delete the instance. Always true in prod."
  type        = bool
}

variable "db_skip_final_snapshot" {
  description = "Whether a destroy may skip the final snapshot. Never true in prod."
  type        = bool
}

variable "sender_email" {
  description = <<-EOT
    Address every message is sent from, verified as a SES identity. This account owns no
    domain, so this is an address rather than a domain — and in the SES sandbox it can
    only deliver to the addresses in `verified_emails`.
  EOT
  type        = string
}

variable "verified_emails" {
  description = "Recipients to verify. In the sandbox, mail to anyone not on this list is refused."
  type        = list(string)
  default     = []
}

variable "ses_sandbox_expected" {
  description = "Recorded expectation. False asserts AWS has granted production access."
  type        = bool
}

variable "alarm_email" {
  description = "Address subscribed to the alarm topic. Confirm the subscription once, from the inbox."
  type        = string
}

variable "log_retention_days" {
  description = "CloudWatch retention. Prod logs are part of the evidentiary picture."
  type        = number
}

variable "test_fixtures_enabled" {
  description = <<-EOT
    Whether this environment carries the `/api/test/*` fixtures an E2E run needs, and with
    them simulated mail: messages are recorded in the API's memory rather than sent, and a
    token holder can read them back.

    **True on the dev stand only.** The suite cannot build its own preconditions through
    the product yet. There is no mail provider — SES is in the sandbox with an unverified
    identity — and the signing link exists nowhere but inside the message, so without a
    simulated mailbox the signing flow cannot be exercised against a deployment at all.
    There is likewise no invite flow, so putting a second person into an organization and
    giving them a role are fixtures too; the suite used to do both by writing to the
    database directly, which only ever worked where the database was reachable.

    It is not free. This environment stops exercising SES entirely, and anyone holding the
    token can read every signing link it has issued. It also pins the API to a single task,
    because an in-memory outbox is per-process. Retire it the day real mail works and spec
    04 lands.
  EOT
  type        = bool
  default     = false
}

variable "alarms_enabled" {
  description = "Whether the service alarms are armed. `make stop-<env>` turns them off with the tasks."
  type        = bool
  default     = true
}

variable "sweep_enabled" {
  description = "Whether the hourly sweep schedule is armed."
  type        = bool
  default     = true
}

variable "retained_images" {
  description = "Images kept per ECR repository. This is how many deploys back you can roll."
  type        = number
  default     = 10
}

# ---------------------------------------------------------------------------------------
# CI/CD — provisioned in both environments, and off by default in both
# ---------------------------------------------------------------------------------------

variable "github_repository" {
  description = "owner/repo whose workflow runs may assume the deploy role."
  type        = string
  default     = "Devscribed/Devscribed.Admin"
}

variable "github_allowed_refs" {
  description = <<-EOT
    Refs allowed to deploy this environment, as OIDC `sub` suffixes. Narrow on purpose:
    any branch anyone can push is a branch that could otherwise deploy.
  EOT
  type        = list(string)
}

variable "create_github_oidc_provider" {
  description = <<-EOT
    There is exactly one GitHub OIDC provider per AWS account. The first environment
    applied creates it; every later one points at the existing ARN. Dev creates it here
    because dev is applied first.
  EOT
  type        = bool
}
