-- CreateTable
CREATE TABLE "VacationReserveTransaction" (
    "id" TEXT NOT NULL,
    "membershipId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "billingPeriodMonth" INTEGER,
    "billingPeriodYear" INTEGER,
    "description" VARCHAR(200),
    "vacationRequestId" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdByAccountId" TEXT,

    CONSTRAINT "VacationReserveTransaction_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "VacationReserveTransaction_membershipId_idx" ON "VacationReserveTransaction"("membershipId");

-- CreateIndex
CREATE UNIQUE INDEX "VacationReserveTransaction_membershipId_billingPeriodMonth__key" ON "VacationReserveTransaction"("membershipId", "billingPeriodMonth", "billingPeriodYear");

-- AddForeignKey
ALTER TABLE "VacationReserveTransaction" ADD CONSTRAINT "VacationReserveTransaction_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "Membership"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VacationReserveTransaction" ADD CONSTRAINT "VacationReserveTransaction_createdByAccountId_fkey" FOREIGN KEY ("createdByAccountId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
